<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zettagenomics.opencga-enterprise</groupId>
        <artifactId>opencga-enterprise</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>opencga-enterprise-app</artifactId>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <dep.jline.version>3.12.1</dep.jline.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.zettagenomics.opencga-enterprise</groupId>
            <artifactId>opencga-enterprise-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-app</artifactId>
            <version>${opencga.version}</version>
        </dependency>
        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-core</artifactId>
            <version>${opencga.version}</version>
        </dependency>
        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-catalog</artifactId>
            <version>${opencga.version}</version>
        </dependency>
        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-analysis</artifactId>
            <version>${opencga.version}</version>
        </dependency>
        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-master</artifactId>
            <version>${opencga.version}</version>
        </dependency>
        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-storage-app</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.opencb.opencga</groupId>
                    <artifactId>opencga-storage-benchmark</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-client</artifactId>
        </dependency>
        <!--        <dependency>-->
        <!--            <groupId>org.opencb.opencga</groupId>-->
        <!--            <artifactId>opencga-test</artifactId>-->
        <!--            <version>${project.parent.version}</version>-->
        <!--            <type>pom</type>-->
        <!--        </dependency>-->
        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-server</artifactId>
            <version>${opencga.version}</version>
            <!--<type>war</type>-->
        </dependency>

        <!--        <dependency>-->
        <!--            <groupId>com.beust</groupId>-->
        <!--            <artifactId>jcommander</artifactId>-->
        <!--            <version>1.82</version>-->
        <!--        </dependency>-->
        <!--        <dependency>-->
        <!--            <groupId>org.glassfish.jersey.containers</groupId>-->
        <!--            <artifactId>jersey-container-servlet-core</artifactId>-->
        <!--            <version>${jersey.version}</version>-->
        <!--        </dependency>-->
        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-analysis</artifactId>
            <version>${opencga.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-storage-core</artifactId>
            <version>${opencga.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-catalog</artifactId>
            <version>${opencga.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.opencb.commons</groupId>
            <artifactId>commons-lib</artifactId>
            <version>4.8.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.opencb.commons</groupId>
            <artifactId>commons-datastore-core</artifactId>
            <version>4.8.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>
        <!--JLINE Terminal dependencies-->
        <dependency>
            <groupId>org.jline</groupId>
            <artifactId>jline-reader</artifactId>
            <version>${dep.jline.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jline</groupId>
            <artifactId>jline-terminal</artifactId>
            <version>${dep.jline.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jline</groupId>
            <artifactId>jline-terminal-jna</artifactId>
            <version>${dep.jline.version}</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>opencga-enterprise-app</finalName>
        <sourceDirectory>src/main/java</sourceDirectory>

        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>appassembler-maven-plugin</artifactId>
                <version>1.10</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>assemble</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <repositoryName>libs</repositoryName>
                    <repositoryLayout>flat</repositoryLayout>
                    <useWildcardClassPath>false</useWildcardClassPath>
                    <!--By default, "etc".-->
                    <configurationDirectory>conf</configurationDirectory>
                    <!--Do we need to include the configuration folder in the classpath?-->
                    <includeConfigurationDirectoryInClasspath>false</includeConfigurationDirectoryInClasspath>
                    <environmentSetupFileName>../conf/${opencga.env.file}</environmentSetupFileName>
                    <programs>
                        <program>
                            <id>opencga-enterprise.sh</id>
                            <mainClass>com.zettagenomics.opencga.enterprise.app.cli.main.OpencgaEnterpriseMain</mainClass>
                            <platforms>
                                <platform>unix</platform>
                            </platforms>
                        </program>
                    </programs>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>