<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.zettagenomics.opencga-enterprise</groupId>
    <artifactId>opencga-enterprise</artifactId>
    <version>3.1.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>opencga-enterprise-app</module>
        <module>opencga-enterprise-client</module>
        <module>opencga-enterprise-core</module>
        <module>opencga-enterprise-catalog</module>
        <module>opencga-enterprise-cvdb</module>
        <module>opencga-enterprise-server</module>
    </modules>

    <properties>
        <opencga.version>4.1.1</opencga.version>
        <cellbase.version>6.6.0</cellbase.version>
        <biodata.version>4.1.0</biodata.version>
        <java-common-libs.version>6.1.0</java-common-libs.version>
        <iva.version>3.1.1</iva.version>

        <oskar.version>0.2.0</oskar.version>

        <jackson.version>2.14.3</jackson.version>
        <jersey.version>2.30.1</jersey.version>
        <collections.version>4.4</collections.version>
        <avro.version>1.7.7</avro.version>
        <protobuf.version>3.11.4</protobuf.version>
        <grpc.version>1.28.1</grpc.version>
        <slf4j.version>1.7.36</slf4j.version>
        <log4j2.version>2.17.2</log4j2.version>
        <solr.version>8.11.3</solr.version>
        <jjwt.version>0.11.2</jjwt.version>
        <jetty.version>9.4.53.v20231009</jetty.version>
        <junit.version>4.13.2</junit.version>
        <jline.version>3.12.1</jline.version>
        <mail.version>1.4.7</mail.version>
        <mockito.version>2.2.27</mockito.version>
        <ga4gh.version>0.6.0a5</ga4gh.version>
        <jcommander.version>1.69</jcommander.version>
        <commons-lang3.version>3.14.0</commons-lang3.version>
        <cas.version>3.6.4</cas.version>
        <servlet-api.version>3.1.0</servlet-api.version>
        <jakarta.version>2.1.6</jakarta.version>
        <javax.ws.rs-api.version>2.0.1</javax.ws.rs-api.version>
        <commons-io.version>2.8.0</commons-io.version>
        <json-smart.version>2.3</json-smart.version>

        <!--        <opencga.war.name>opencga-enterprise</opencga.war.name>-->
        <opencga.env.file>opencga-env.sh</opencga.env.file>
        <opencga.hadoop.thirdparty.version>1.0.0-SNAPSHOT</opencga.hadoop.thirdparty.version>
        <opencga-hadoop-shaded.id-default>hdp3.1</opencga-hadoop-shaded.id-default>

        <opencga-storage-hadoop-lib.artifactId-default>opencga-storage-hadoop-${opencga-hadoop-shaded.id-default}</opencga-storage-hadoop-lib.artifactId-default>
        <opencga-hadoop-shaded.id>${opencga-hadoop-shaded.id-default}</opencga-hadoop-shaded.id>
        <opencga-storage-hadoop-lib.artifactId>opencga-storage-hadoop-lib-${opencga-hadoop-shaded.id}</opencga-storage-hadoop-lib.artifactId>
        <opencga-storage-hadoop-thirdparty.artifactId>opencga-hadoop-shaded-${opencga-hadoop-shaded.id}</opencga-storage-hadoop-thirdparty.artifactId>


        <sonar.organization>opencb</sonar.organization>
        <sonar.host.url>https://sonarcloud.io</sonar.host.url>

        <!-- This prevents findbugs plugin to check all the dependency locations -->
        <dependency.locations.enabled>false</dependency.locations.enabled>
        <maven.compiler.source>1.8</maven.compiler.source>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <guava.version>28.0-jre</guava.version>
<!--        <commons-lang.version>2.6</commons-lang.version>-->
        <bson.version>4.8.2</bson.version>
    </properties>

    <repositories>
        <repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>
            </snapshots>
        </repository>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/opencb</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.zettagenomics.opencga-enterprise</groupId>
                <artifactId>opencga-enterprise-core</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.zettagenomics.opencga-enterprise</groupId>
                <artifactId>opencga-enterprise-client</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.zettagenomics.opencga-enterprise</groupId>
                <artifactId>opencga-enterprise-cvdb</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.zettagenomics.opencga-enterprise</groupId>
                <artifactId>opencga-enterprise-catalog</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.zettagenomics.opencga-enterprise</groupId>
                <artifactId>opencga-enterprise-server</artifactId>
                <version>${project.parent.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>commons-collections</groupId>
                        <artifactId>commons-collections</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <!-- OpenCB dependencies -->
            <dependency>
                <groupId>org.opencb.opencga</groupId>
                <artifactId>opencga-core</artifactId>
                <version>${opencga.version}</version>
            </dependency>
            <dependency>
                <groupId>org.opencb.opencga</groupId>
                <artifactId>opencga-catalog</artifactId>
                <version>${opencga.version}</version>
            </dependency>
            <dependency>
                <groupId>org.opencb.opencga</groupId>
                <artifactId>opencga-catalog</artifactId>
                <version>${opencga.version}</version>
                <type>test-jar</type>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.opencb.opencga</groupId>
                <artifactId>opencga-analysis</artifactId>
                <version>${opencga.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.opencb.opencga</groupId>
                        <artifactId>${opencga-storage-hadoop-deps.artifactId-default}</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.opencb.opencga</groupId>
                <artifactId>opencga-storage-app</artifactId>
                <version>${opencga.version}</version>
            </dependency>
            <dependency>
                <groupId>org.opencb.opencga</groupId>
                <artifactId>opencga-app</artifactId>
                <version>${opencga.version}</version>
            </dependency>
            <dependency>
                <groupId>org.opencb.opencga</groupId>
                <artifactId>opencga-server</artifactId>
                <version>${opencga.version}</version>
            </dependency>
            <dependency>
                <groupId>org.opencb.opencga</groupId>
                <artifactId>opencga-storage-core</artifactId>
                <version>${opencga.version}</version>
            </dependency>
            <dependency>
                <groupId>org.opencb.opencga</groupId>
                <artifactId>${opencga-storage-hadoop-lib.artifactId}</artifactId>
                <version>${opencga.version}</version>
                <exclusions>
                    <!-- This dependency version conflicts with opencga-core's same dependency version. -->
                    <!-- Exclude this, so the actual dependency can be taken from opencga-core -->
                    <exclusion>
                        <groupId>org.apache.httpcomponents</groupId>
                        <artifactId>httpclient</artifactId>
                    </exclusion>
                </exclusions>
                <classifier>shaded</classifier>
            </dependency>
            <dependency>
                <groupId>org.opencb.opencga</groupId>
                <artifactId>opencga-client</artifactId>
                <version>${opencga.version}</version>
            </dependency>
            <dependency>
                <groupId>org.opencb.oskar</groupId>
                <artifactId>oskar-analysis</artifactId>
                <version>${oskar.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-log4j12</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.opencb.biodata</groupId>
                <artifactId>biodata-formats</artifactId>
                <version>${biodata.version}</version>
            </dependency>
            <dependency>
                <groupId>org.opencb.biodata</groupId>
                <artifactId>biodata-models</artifactId>
                <version>${biodata.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.google.protobuf</groupId>
                        <artifactId>protobuf-lite</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.mortbay.jetty</groupId>
                        <artifactId>servlet-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.opencb.biodata</groupId>
                <artifactId>biodata-tools</artifactId>
                <version>${biodata.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.avro</groupId>
                        <artifactId>avro-ipc</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.opencb.commons</groupId>
                <artifactId>commons-lib</artifactId>
                <version>${java-common-libs.version}</version>
            </dependency>
            <dependency>
                <groupId>org.opencb.commons</groupId>
                <artifactId>commons-datastore-core</artifactId>
                <version>${java-common-libs.version}</version>
            </dependency>
            <dependency>
                <groupId>org.opencb.cellbase</groupId>
                <artifactId>cellbase-client</artifactId>
                <version>${cellbase.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-log4j12</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.opencb.commons</groupId>
                <artifactId>commons-datastore-mongodb</artifactId>
                <version>${java-common-libs.version}</version>
            </dependency>
            <dependency>
                <groupId>org.opencb.commons</groupId>
                <artifactId>commons-datastore-solr</artifactId>
                <version>${java-common-libs.version}</version>
            </dependency>
            <dependency>
                <groupId>org.opencb.ga4gh</groupId>
                <artifactId>ga4gh</artifactId>
                <version>${ga4gh.version}</version>
            </dependency>

            <!-- General dependencies -->
            <dependency>
                <groupId>org.apache.solr</groupId>
                <artifactId>solr-solrj</artifactId>
                <version>${solr.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>${collections.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-slf4j-impl</artifactId>
                <version>${log4j2.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-core</artifactId>
                <version>${log4j2.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-joda</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-yaml</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-xml</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-cbor</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>javax.mail</groupId>
                <artifactId>mail</artifactId>
                <version>${mail.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-server</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-webapp</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-servlet</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-http</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-io</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-util</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-client</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-project</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-alpn-client</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-alpn-java-client</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jersey.containers</groupId>
                <artifactId>jersey-container-servlet</artifactId>
                <version>${jersey.version}</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jersey.inject</groupId>
                <artifactId>jersey-hk2</artifactId>
                <version>${jersey.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt.version}</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt.version}</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>net.minidev</groupId>
                <artifactId>json-smart</artifactId>
                <version>${json-smart.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-java</artifactId>
                <version>${protobuf.version}</version>
            </dependency>
            <dependency>
                <groupId>net.minidev</groupId>
                <artifactId>json-smart</artifactId>
                <version>${json-smart.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-java-util</artifactId>
                <version>${protobuf.version}</version>
            </dependency>
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-all</artifactId>
                <version>${grpc.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro</artifactId>
                <version>${avro.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-ipc</artifactId>
                <version>${avro.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-mapred</artifactId>
                <version>${avro.version}</version>
                <classifier>hadoop2</classifier>
            </dependency>
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-api</artifactId>
                <version>${grpc.version}</version>
            </dependency>
            <dependency>
                <groupId>com.beust</groupId>
                <artifactId>jcommander</artifactId>
                <version>${jcommander.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jline</groupId>
                <artifactId>jline-reader</artifactId>
                <version>${jline.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons-lang3.version}</version>
            </dependency>
            <dependency>
                <groupId>javax.ws.rs</groupId>
                <artifactId>javax.ws.rs-api</artifactId>
                <version>${javax.ws.rs-api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jasig.cas.client</groupId>
                <artifactId>cas-client-core</artifactId>
                <version>${cas.version}</version>
            </dependency>
            <dependency>
                <groupId>jakarta.ws.rs</groupId>
                <artifactId>jakarta.ws.rs-api</artifactId>
                <version>${jakarta.version}</version>
            </dependency>
            <dependency>
                <groupId>javax.servlet</groupId>
                <artifactId>javax.servlet-api</artifactId>
                <version>${servlet-api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jersey.core</groupId>
                <artifactId>jersey-server</artifactId>
                <version>${jersey.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jasig.cas.client</groupId>
                <artifactId>cas-client-support-saml</artifactId>
                <version>${cas.version}</version>
            </dependency>
            <!-- Test dependencies -->
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-simple</artifactId>
                <version>1.7.5</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.solr</groupId>
                <artifactId>solr-test-framework</artifactId>
                <version>${solr.version}</version>
                <scope>test</scope>
                <exclusions>
                    <exclusion>
                        <groupId>com.google.protobuf</groupId>
                        <artifactId>protobuf-java</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-slf4j-impl</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-1.2-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-web</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.solr</groupId>
                <artifactId>solr-core</artifactId>
                <version>${solr.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons-io.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-api</artifactId>
                <version>${log4j2.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mongodb</groupId>
                <artifactId>bson</artifactId>
                <version>${bson.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>default-config</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <opencga.war.name>opencga-enterprise-${project.parent.version}</opencga.war.name>

                <ENTERPRISE.SSO.ACTIVE>false</ENTERPRISE.SSO.ACTIVE>
                <ENTERPRISE.SSO.CAS.SERVER.PREFIX.URL>https://localhost:8443/cas</ENTERPRISE.SSO.CAS.SERVER.PREFIX.URL>
                <ENTERPRISE.SSO.SERVER.NAME>http://localhost:9090</ENTERPRISE.SSO.SERVER.NAME>
                <ENTERPRISE.SSO.PROTOCOL>SAML1</ENTERPRISE.SSO.PROTOCOL>
                <ENTERPRISE.SSO.ATTRIBUTES.NAME>name</ENTERPRISE.SSO.ATTRIBUTES.NAME>
                <ENTERPRISE.SSO.ATTRIBUTES.SURNAME>surname</ENTERPRISE.SSO.ATTRIBUTES.SURNAME>
                <ENTERPRISE.SSO.ATTRIBUTES.EMAIL>email</ENTERPRISE.SSO.ATTRIBUTES.EMAIL>
                <ENTERPRISE.SSO.ATTRIBUTES.ORGANIZATION>organization</ENTERPRISE.SSO.ATTRIBUTES.ORGANIZATION>
                <ENTERPRISE.SSO.ATTRIBUTES.GROUPS>groups</ENTERPRISE.SSO.ATTRIBUTES.GROUPS>

                <ENTERPRISE.CVDB.ACTIVE>true</ENTERPRISE.CVDB.ACTIVE>
                <ENTERPRISE.CVDB.DATABASE.HOST>http://localhost:8983/solr/</ENTERPRISE.CVDB.DATABASE.HOST>
                <ENTERPRISE.CVDB.DATABASE.MODE>cloud</ENTERPRISE.CVDB.DATABASE.MODE>
                <ENTERPRISE.CVDB.DATABASE.TIMEOUT>30000</ENTERPRISE.CVDB.DATABASE.TIMEOUT>
                <ENTERPRISE.CVDB.CA_CONFIG_SET>opencga-ca-configset-${project.parent.version}</ENTERPRISE.CVDB.CA_CONFIG_SET>
                <ENTERPRISE.CVDB.CI_CONFIG_SET>opencga-ci-configset-${project.parent.version}</ENTERPRISE.CVDB.CI_CONFIG_SET>
                <ENTERPRISE.CVDB.CV_CONFIG_SET>opencga-cv-configset-${project.parent.version}</ENTERPRISE.CVDB.CV_CONFIG_SET>
                <ENTERPRISE.CVDB.CVE_CONFIG_SET>opencga-cve-configset-${project.parent.version}</ENTERPRISE.CVDB.CVE_CONFIG_SET>

                <!-- General -->
                <OPENCGA.INSTALLATION.DIR>/opt/opencga</OPENCGA.INSTALLATION.DIR>
                <OPENCGA.USER.WORKSPACE>/opt/opencga/sessions</OPENCGA.USER.WORKSPACE>
                <OPENCGA.ANALYSIS.SCRATCH.DIR></OPENCGA.ANALYSIS.SCRATCH.DIR>
                <OPENCGA.DB.PREFIX>opencga</OPENCGA.DB.PREFIX>
                <OPENCGA.EXECUTION.MODE>LOCAL</OPENCGA.EXECUTION.MODE>

                <!-- Client -->
                <OPENCGA.CLIENT.REST.HOST>https://ws.opencb.org/opencga-prod</OPENCGA.CLIENT.REST.HOST>
                <OPENCGA.CLIENT.GRPC.HOST>localhost:9091</OPENCGA.CLIENT.GRPC.HOST>

                <OPENCGA.SERVER.REST.PORT>9090</OPENCGA.SERVER.REST.PORT>
                <OPENCGA.SERVER.GRPC.PORT>9091</OPENCGA.SERVER.GRPC.PORT>
                <OPENCGA.MONITOR.PORT>9092</OPENCGA.MONITOR.PORT>

                <!-- Catalog -->
                <OPENCGA.CATALOG.DB.HOSTS>localhost:27017</OPENCGA.CATALOG.DB.HOSTS>
                <OPENCGA.CATALOG.DB.USER></OPENCGA.CATALOG.DB.USER>
                <OPENCGA.CATALOG.DB.PASSWORD></OPENCGA.CATALOG.DB.PASSWORD>
                <OPENCGA.CATALOG.DB.AUTHENTICATION_DATABASE></OPENCGA.CATALOG.DB.AUTHENTICATION_DATABASE>
                <OPENCGA.CATALOG.DB.CONNECTIONS_PER_HOST>20</OPENCGA.CATALOG.DB.CONNECTIONS_PER_HOST>
                <OPENCGA.CATALOG.SEARCH.HOST>http://localhost:8983/solr/</OPENCGA.CATALOG.SEARCH.HOST>
                <OPENCGA.CATALOG.SEARCH.TIMEOUT>30000</OPENCGA.CATALOG.SEARCH.TIMEOUT>
                <OPENCGA.CATALOG.SEARCH.BATCH>2000</OPENCGA.CATALOG.SEARCH.BATCH>

                <!-- Optimizations -->
                <OPENCGA_OPTIMIZATIONS_SIMPLIFY_PERMISSIONS>false</OPENCGA_OPTIMIZATIONS_SIMPLIFY_PERMISSIONS>

                <!-- Storage -->
                <OPENCGA.STORAGE.DEFAULT_ENGINE>hadoop</OPENCGA.STORAGE.DEFAULT_ENGINE>
                <OPENCGA.STORAGE.CACHE.HOST>localhost:6379</OPENCGA.STORAGE.CACHE.HOST>

                <!-- Storage Variants general -->
                <OPENCGA.STORAGE.VARIANT.DB.HOSTS>localhost:27017</OPENCGA.STORAGE.VARIANT.DB.HOSTS>
                <OPENCGA.STORAGE.VARIANT.DB.USER></OPENCGA.STORAGE.VARIANT.DB.USER>
                <OPENCGA.STORAGE.VARIANT.DB.PASSWORD></OPENCGA.STORAGE.VARIANT.DB.PASSWORD>
                <OPENCGA.STORAGE.SEARCH.HOST>http://localhost:8983/solr/</OPENCGA.STORAGE.SEARCH.HOST>
                <OPENCGA.STORAGE.SEARCH.CONFIG_SET>opencga-variant-configset-${project.parent.version}</OPENCGA.STORAGE.SEARCH.CONFIG_SET>
                <OPENCGA.STORAGE.SEARCH.TIMEOUT>30000</OPENCGA.STORAGE.SEARCH.TIMEOUT>
                <OPENCGA.STORAGE.CLINICAL.HOST>http://localhost:8983/solr/</OPENCGA.STORAGE.CLINICAL.HOST>
                <OPENCGA.STORAGE.CLINICAL.MANAGER>""</OPENCGA.STORAGE.CLINICAL.MANAGER>
                <OPENCGA.STORAGE.CLINICAL.TIMEOUT>30000</OPENCGA.STORAGE.CLINICAL.TIMEOUT>
                <OPENCGA.STORAGE.RGA.HOST>http://localhost:8983/solr/</OPENCGA.STORAGE.RGA.HOST>
                <OPENCGA.STORAGE.RGA.CONFIG_SET>opencga-rga-configset-${project.parent.version}</OPENCGA.STORAGE.RGA.CONFIG_SET>
                <OPENCGA.STORAGE.RGA.TIMEOUT>30000</OPENCGA.STORAGE.RGA.TIMEOUT>

                <!-- Storage Alignments general -->
                <OPENCGA.STORAGE.ALIGNMENT.DB.HOSTS>localhost:27017</OPENCGA.STORAGE.ALIGNMENT.DB.HOSTS>
                <OPENCGA.STORAGE.ALIGNMENT.DB.USER></OPENCGA.STORAGE.ALIGNMENT.DB.USER>
                <OPENCGA.STORAGE.ALIGNMENT.DB.PASSWORD></OPENCGA.STORAGE.ALIGNMENT.DB.PASSWORD>

                <!-- Storage-mongodb -->
<!--                <OPENCGA.STORAGE.MONGODB.VARIANT.DB.AUTHENTICATION_DATABASE></OPENCGA.STORAGE.MONGODB.VARIANT.DB.AUTHENTICATION_DATABASE>-->
<!--                <OPENCGA.STORAGE.MONGODB.VARIANT.DB.CONNECTIONS_PER_HOST>20</OPENCGA.STORAGE.MONGODB.VARIANT.DB.CONNECTIONS_PER_HOST>-->

                <!-- Storage-hadoop -->
                <OPENCGA.STORAGE.HADOOP.VARIANT.DB.USER></OPENCGA.STORAGE.HADOOP.VARIANT.DB.USER>
                <OPENCGA.STORAGE.HADOOP.VARIANT.DB.PASSWORD></OPENCGA.STORAGE.HADOOP.VARIANT.DB.PASSWORD>
                <OPENCGA.STORAGE.HADOOP.VARIANT.HBASE.NAMESPACE></OPENCGA.STORAGE.HADOOP.VARIANT.HBASE.NAMESPACE>

                <!-- Email server -->
                <OPENCGA.MAIL.HOST></OPENCGA.MAIL.HOST>
                <OPENCGA.MAIL.PORT></OPENCGA.MAIL.PORT>
                <OPENCGA.MAIL.USER></OPENCGA.MAIL.USER>
                <OPENCGA.MAIL.PASSWORD></OPENCGA.MAIL.PASSWORD>

                <!-- cellbase -->
                <OPENCGA.CELLBASE.REST.HOST>https://uk.ws.zettagenomics.com/cellbase/</OPENCGA.CELLBASE.REST.HOST>
                <OPENCGA.CELLBASE.VERSION>v5.2</OPENCGA.CELLBASE.VERSION>
            </properties>
        </profile>
    </profiles>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>analyze</id>
                        <goals>
                            <goal>analyze-only</goal>
                        </goals>
                        <configuration>
                            <failOnWarning>true</failOnWarning>
                            <ignoredUnusedDeclaredDependencies>
                                <ignoredUnusedDeclaredDependency>*</ignoredUnusedDeclaredDependency>
                            </ignoredUnusedDeclaredDependencies>
                            <ignoredUsedUndeclaredDependencies>
                                <ignoredUsedUndeclaredDependency>
                                    jakarta.ws.rs:jakarta.ws.rs-api*
                                </ignoredUsedUndeclaredDependency>
                                <ignoredUsedUndeclaredDependency>
                                    javax.ws.rs:jsr311-api
                                </ignoredUsedUndeclaredDependency>
                            </ignoredUsedUndeclaredDependencies>
                            <ignoredNonTestScopedDependencies>
                                <ignoredNonTestScopedDependency>*</ignoredNonTestScopedDependency>
                            </ignoredNonTestScopedDependencies>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
