name: Build OpenCGA Enterprise

on:
  workflow_call:
    inputs:
      storage_hadoop:
        type: string
        required: false
      artifact_name:
        type: string
        required: false
      release:
        type: string
        required: false
        default: ""
      python_client:
        type: string
        required: false
        default: "false"
      r_client:
        type: string
        required: false
        default: "false"
      javascript_client:
        type: string
        required: false
        default: "false"
      branch:
        type: string
        description: "Opencga-enterprise ref to use (optional) used only for manual builds"
        required: false
        default: ""
      task:
        type: string
        description: "Task to use to compile dependencies (optional) used only for manual builds"
        required: false
        default: ""
    outputs:
      version:
        description: "XetaBase project version"
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    name: Build OpenCGA Enterprise app
    runs-on: ${{ vars.UBUNTU_VERSION }}
    outputs:
      version: ${{ steps.get_project_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
          ref: ${{ inputs.branch || github.ref_name }}
      - run: |
          echo "Checked out: ${{ inputs.branch || github.ref_name }}"
      - id: get_opencga_branch
        name: Get OpenCGA branch from pom.xml property
        run: |
          chmod +x ./.github/workflows/scripts/opencga_branch.sh
          opencga_branch=$(./.github/workflows/scripts/opencga_branch.sh "${{ inputs.release }}" )
          echo "OpenCGA ref: __\"${opencga_branch}\"__" | tee -a ${GITHUB_STEP_SUMMARY}
          echo "Is release: __\"${{ inputs.release }}\"__" | tee -a ${GITHUB_STEP_SUMMARY}
          echo "opencga_branch=${opencga_branch}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          repository: opencb/opencga
          ref: ${{ steps.get_opencga_branch.outputs.opencga_branch }}
          path: opencga-home
          fetch-depth: '10'
      - run: |
          echo "Opencga ref: ${{ steps.get_opencga_branch.outputs.opencga_branch }}"
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Clone dependencies
        id: clone_dependencies
        run: |
          if [ -f "./.github/workflows/scripts/get_same_branch.sh" ]; then
            chmod +x ./.github/workflows/scripts/get_same_branch.sh
            export DEPENDENCIES_SHA=${{ github.sha }}
            ./.github/workflows/scripts/get_same_branch.sh ${{ github.ref_name }}
          fi
      - name: Cache local Maven repository
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ inputs.storage_hadoop }}-${{ steps.clone_dependencies.outputs.dependencies_sha }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ inputs.storage_hadoop }}-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: OpenCGA Enterprise Maven Build (skip tests)
        run: |
          CLIENTS=""
          if [ "${{ inputs.python_client }}" == "true" ]; then
            echo "Building Python client"
            CLIENTS="$CLIENTS --python-client"
          fi
          if [ "${{ inputs.r_client }}" == "true" ]; then
              echo "Building R client"
              CLIENTS="$CLIENTS --R-client"
          fi
          if [ "${{ inputs.javascript_client }}" == "true" ]; then
              echo "Building JavaScript client"
              CLIENTS="$CLIENTS --javascript-client"
          fi
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          if [[ -n "${{ inputs.task }}" ]]; then 
            branch_name="${{ inputs.task }}"
          fi
          ./build.sh --storage-hadoop ${{ inputs.storage_hadoop }} --prepare-branches --prepare-hadoop --task "$branch_name" $CLIENTS
        env:
          THIRDPARTY_READ_TOKEN: ${{ secrets.THIRDPARTY_READ_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: build
      - id: get_project_version
        name: Get project version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: test-version-from-check
        run: echo "Project version is " ${{ steps.get_project_version.outputs.version }}
      - name: Upload log
        uses: actions/upload-artifact@v4
        ## Skip cancelled()
        ## https://docs.github.com/en/actions/learn-github-actions/expressions#cancelled
        if: success() || failure()
        with:
          name: build-log
          path: |
            ./build.log
            ./reports/*.log.gz
          if-no-files-found: error