/*
 * Copyright 2015-2020 OpenCB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opencb.opencga.analysis.alignment.qc;

import org.apache.commons.lang3.StringUtils;
import org.opencb.commons.datastore.core.Event;
import org.opencb.commons.datastore.core.ObjectMap;
import org.opencb.commons.datastore.core.Query;
import org.opencb.commons.datastore.core.QueryOptions;
import org.opencb.opencga.analysis.AnalysisUtils;
import org.opencb.opencga.analysis.tools.OpenCgaToolScopeStudy;
import org.opencb.opencga.catalog.exceptions.CatalogException;
import org.opencb.opencga.core.api.ParamConstants;
import org.opencb.opencga.core.exceptions.ToolException;
import org.opencb.opencga.core.models.alignment.AlignmentFastQcMetricsParams;
import org.opencb.opencga.core.models.alignment.AlignmentFlagStatsParams;
import org.opencb.opencga.core.models.alignment.AlignmentQcParams;
import org.opencb.opencga.core.models.alignment.AlignmentStatsParams;
import org.opencb.opencga.core.models.common.Enums;
import org.opencb.opencga.core.models.job.Job;
import org.opencb.opencga.core.response.OpenCGAResult;
import org.opencb.opencga.core.tools.annotations.Tool;
import org.opencb.opencga.core.tools.annotations.ToolParams;

import java.util.Collections;
import java.util.Map;

import static org.opencb.opencga.core.api.ParamConstants.ALIGNMENT_QC_DESCRIPTION;

@Tool(id = AlignmentQcAnalysis.ID, resource = Enums.Resource.ALIGNMENT)
public class AlignmentQcAnalysis extends OpenCgaToolScopeStudy {

    public static final String ID = "alignment-qc";
    public static final String DESCRIPTION = ALIGNMENT_QC_DESCRIPTION;

    @ToolParams
    protected final AlignmentQcParams analysisParams = new AlignmentQcParams();

    @Override
    protected void check() throws Exception {
        super.check();

        if (StringUtils.isEmpty(getStudy())) {
            throw new ToolException("Missing study");
        }

        try {
            AnalysisUtils.getCatalogFile(analysisParams.getFile(), study, catalogManager.getFileManager(), token);
        } catch (CatalogException e) {
            throw new ToolException(e);
        }
    }


    @Override
    protected void run() throws ToolException {

        step(() -> {
            try {
                // Stats
                Map<String, Object> statsParams = new AlignmentStatsParams(analysisParams.getFile(), null)
                        .toParams(new ObjectMap(ParamConstants.STUDY_PARAM, study));

                OpenCGAResult<Job> statsJobResult = catalogManager.getJobManager()
                        .submit(study, AlignmentStatsAnalysis.ID, Enums.Priority.MEDIUM, statsParams, null, "Job generated by "
                                + getId() + " - " + getJobId(), Collections.emptyList(), Collections.emptyList(), token);
                addEvent(Event.Type.INFO, "Submit job " + statsJobResult.first().getId() + " to compute stats ("
                        + AlignmentStatsAnalysis.ID + ")");

                // Flag stats
                Map<String, Object> flagStatsParams = new AlignmentFlagStatsParams(analysisParams.getFile(), null)
                        .toParams(new ObjectMap(ParamConstants.STUDY_PARAM, study));

                OpenCGAResult<Job> flagStatsJobResult = catalogManager.getJobManager()
                        .submit(study, AlignmentFlagStatsAnalysis.ID, Enums.Priority.MEDIUM, flagStatsParams, null, "Job generated by "
                                + getId() + " - " + getJobId(), Collections.emptyList(), Collections.emptyList(), token);
                addEvent(Event.Type.INFO, "Submit job " + flagStatsJobResult.first().getId() + " to compute stats ("
                        + AlignmentFlagStatsAnalysis.ID + ")");

                // FastQC metrics
                Map<String, Object> fastQcMetricsParams = new AlignmentFastQcMetricsParams(analysisParams.getFile(), null)
                        .toParams(new ObjectMap(ParamConstants.STUDY_PARAM, study));

                OpenCGAResult<Job> fastQcMetricsJobResult = catalogManager.getJobManager()
                        .submit(study, AlignmentFastQcMetricsAnalysis.ID, Enums.Priority.MEDIUM, fastQcMetricsParams, null,
                                "Job generated by " + getId() + " - " + getJobId(), Collections.emptyList(), Collections.emptyList(),
                                token);
                addEvent(Event.Type.INFO, "Submit job " + fastQcMetricsJobResult.first().getId() + " to compute FastQC metrics ("
                        + AlignmentFastQcMetricsAnalysis.ID + ")");

                // Wait for those jobs ???
//                waitFor(statsJobResult.first().getId());
//                waitFor(flagStatsJobResult.first().getId());
//                waitFor(fastQcMetricsJobResult.first().getId());
            } catch (CatalogException e) {
                throw new ToolException(e);
            }
        });
    }

    private void waitFor(String jobId) throws InterruptedException, CatalogException, ToolException {
        Job job;
        String status;
        Query query = new Query("id", jobId);
        do {
            Thread.sleep(3000);
            OpenCGAResult<Job> result = catalogManager.getJobManager().search(study, query, QueryOptions.empty(), token);
            job = result.first();
            status = job.getInternal().getStatus().getName();
        } while  (status.equals(Enums.ExecutionStatus.PENDING) || status.equals(Enums.ExecutionStatus.RUNNING)
                || status.equals(Enums.ExecutionStatus.QUEUED) || status.equals(Enums.ExecutionStatus.READY)
                || status.equals(Enums.ExecutionStatus.REGISTERING));

        addEvent(Event.Type.INFO, "Submitted job " + job.getId() + " to compute flag stats (" + job.getTool().getId() + "), execution"
                + " status: " + job.getInternal().getStatus());
    }
}
