package org.opencb.opencga.app.cli.main.executors;

import org.opencb.opencga.app.cli.main.executors.OpencgaCommandExecutor;
import org.opencb.opencga.app.cli.main.*;
import org.opencb.opencga.core.response.RestResponse;
import org.opencb.opencga.client.exceptions.ClientException;
import org.opencb.commons.datastore.core.ObjectMap;

import org.opencb.opencga.catalog.exceptions.CatalogAuthenticationException;
import org.opencb.opencga.core.common.JacksonUtils;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.List;
import java.util.HashMap;
import org.opencb.opencga.core.response.QueryType;
import org.opencb.commons.utils.PrintUtils;

import org.opencb.opencga.app.cli.main.options.FilesCommandOptions;

import org.opencb.opencga.app.cli.main.parent.ParentFilesCommandExecutor;

import java.io.DataInputStream;
import java.io.InputStream;
import java.util.Map;
import org.opencb.biodata.models.clinical.interpretation.Software;
import org.opencb.commons.datastore.core.FacetField;
import org.opencb.opencga.catalog.utils.ParamUtils.AclAction;
import org.opencb.opencga.catalog.utils.ParamUtils.BasicUpdateAction;
import org.opencb.opencga.catalog.utils.ParamUtils.CompleteUpdateAction;
import org.opencb.opencga.core.models.alignment.AlignmentFileQualityControl;
import org.opencb.opencga.core.models.alignment.CoverageFileQualityControl;
import org.opencb.opencga.core.models.common.StatusParams;
import org.opencb.opencga.core.models.common.TsvAnnotationParams;
import org.opencb.opencga.core.models.file.File.Bioformat;
import org.opencb.opencga.core.models.file.File.Format;
import org.opencb.opencga.core.models.file.File;
import org.opencb.opencga.core.models.file.FileAclUpdateParams;
import org.opencb.opencga.core.models.file.FileContent;
import org.opencb.opencga.core.models.file.FileCreateParams;
import org.opencb.opencga.core.models.file.FileExperiment;
import org.opencb.opencga.core.models.file.FileFetch;
import org.opencb.opencga.core.models.file.FileLinkInternalParams;
import org.opencb.opencga.core.models.file.FileLinkParams;
import org.opencb.opencga.core.models.file.FileLinkToolParams;
import org.opencb.opencga.core.models.file.FileQualityControl;
import org.opencb.opencga.core.models.file.FileStatus;
import org.opencb.opencga.core.models.file.FileTree;
import org.opencb.opencga.core.models.file.FileUpdateParams;
import org.opencb.opencga.core.models.file.MissingSamples;
import org.opencb.opencga.core.models.file.PostLinkToolParams;
import org.opencb.opencga.core.models.file.SmallFileInternal;
import org.opencb.opencga.core.models.job.Job;
import org.opencb.opencga.core.models.variant.VariantFileQualityControl;


/*
* WARNING: AUTOGENERATED CODE
*
* This code was generated by a tool.
* Autogenerated on: 2022-05-20
*
* Manual changes to this file may cause unexpected behavior in your application.
* Manual changes to this file will be overwritten if the code is regenerated.
*/


/**
 * This class contains methods for the Files command line.
 *    OpenCGA version: 2.3.0
 *    PATH: /{apiVersion}/files
 */
public class FilesCommandExecutor extends ParentFilesCommandExecutor {

    private FilesCommandOptions filesCommandOptions;

    public FilesCommandExecutor(FilesCommandOptions filesCommandOptions) throws CatalogAuthenticationException {
        super(filesCommandOptions.commonCommandOptions,filesCommandOptions);
        this.filesCommandOptions = filesCommandOptions;
    }

    @Override
    public void execute() throws Exception {

        logger.debug("Executing Files command line");

        String subCommandString = getParsedSubCommand(filesCommandOptions.jCommander);

        RestResponse queryResponse = null;

        switch (subCommandString) {
            case "acl-update":
                queryResponse = updateAcl();
                break;
            case "aggregationstats":
                queryResponse = aggregationStats();
                break;
            case "annotation-sets-load":
                queryResponse = loadAnnotationSets();
                break;
            case "create":
                queryResponse = create();
                break;
            case "distinct":
                queryResponse = distinct();
                break;
            case "fetch":
                queryResponse = fetch();
                break;
            case "link":
                queryResponse = link();
                break;
            case "link-run":
                queryResponse = runLink();
                break;
            case "postlink-run":
                queryResponse = runPostlink();
                break;
            case "search":
                queryResponse = search();
                break;
            case "upload":
                queryResponse = upload();
                break;
            case "acl":
                queryResponse = acl();
                break;
            case "delete":
                queryResponse = delete();
                break;
            case "info":
                queryResponse = info();
                break;
            case "unlink":
                queryResponse = unlink();
                break;
            case "update":
                queryResponse = update();
                break;
            case "annotation-sets-annotations-update":
                queryResponse = updateAnnotationSetsAnnotations();
                break;
            case "download":
                queryResponse = download();
                break;
            case "grep":
                queryResponse = grep();
                break;
            case "head":
                queryResponse = head();
                break;
            case "image":
                queryResponse = image();
                break;
            case "refresh":
                queryResponse = refresh();
                break;
            case "tail":
                queryResponse = tail();
                break;
            case "list":
                queryResponse = list();
                break;
            case "tree":
                queryResponse = tree();
                break;
            default:
                logger.error("Subcommand not valid");
                break;
        }

        createOutput(queryResponse);

    }

    private RestResponse<ObjectMap> updateAcl() throws Exception {

        logger.debug("Executing updateAcl in Files command line");

        FilesCommandOptions.UpdateAclCommandOptions commandOptions = filesCommandOptions.updateAclCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }


        FileAclUpdateParams fileAclUpdateParams = new FileAclUpdateParams();
        if (commandOptions.jsonDataModel) {
            RestResponse<ObjectMap> res = new RestResponse<>();
            res.setType(QueryType.VOID);
            PrintUtils.println(getObjectAsJSON(fileAclUpdateParams));
            return res;
        } else if (commandOptions.jsonFile != null) {
            fileAclUpdateParams = JacksonUtils.getDefaultObjectMapper()
                    .readValue(new java.io.File(commandOptions.jsonFile), FileAclUpdateParams.class);
        } else {
            fileAclUpdateParams.setPermissions(commandOptions.permissions);
            fileAclUpdateParams.setFile(commandOptions.file);
            fileAclUpdateParams.setSample(commandOptions.sample);

        }
        return openCGAClient.getFileClient().updateAcl(commandOptions.members, commandOptions.action, fileAclUpdateParams, queryParams);
    }

    private RestResponse<FacetField> aggregationStats() throws Exception {

        logger.debug("Executing aggregationStats in Files command line");

        FilesCommandOptions.AggregationStatsCommandOptions commandOptions = filesCommandOptions.aggregationStatsCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("name", commandOptions.name);
        queryParams.putIfNotEmpty("type", commandOptions.type);
        queryParams.putIfNotEmpty("format", commandOptions.format);
        queryParams.putIfNotEmpty("bioformat", commandOptions.bioformat);
        queryParams.putIfNotEmpty("creationYear", commandOptions.creationYear);
        queryParams.putIfNotEmpty("creationMonth", commandOptions.creationMonth);
        queryParams.putIfNotEmpty("creationDay", commandOptions.creationDay);
        queryParams.putIfNotEmpty("creationDayOfWeek", commandOptions.creationDayOfWeek);
        queryParams.putIfNotEmpty("status", commandOptions.status);
        queryParams.putIfNotEmpty("release", commandOptions.release);
        queryParams.putIfNotNull("external", commandOptions.external);
        queryParams.putIfNotEmpty("size", commandOptions.size);
        queryParams.putIfNotEmpty("software", commandOptions.software);
        queryParams.putIfNotEmpty("experiment", commandOptions.experiment);
        queryParams.putIfNotEmpty("numSamples", commandOptions.numSamples);
        queryParams.putIfNotEmpty("numRelatedFiles", commandOptions.numRelatedFiles);
        queryParams.putIfNotEmpty("annotation", commandOptions.annotation);
        queryParams.putIfNotNull("default_values", commandOptions.default_values);
        queryParams.putIfNotEmpty("field", commandOptions.field);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().aggregationStats(queryParams);
    }

    private RestResponse<Job> loadAnnotationSets() throws Exception {

        logger.debug("Executing loadAnnotationSets in Files command line");

        FilesCommandOptions.LoadAnnotationSetsCommandOptions commandOptions = filesCommandOptions.loadAnnotationSetsCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotNull("parents", commandOptions.parents);
        queryParams.putIfNotEmpty("annotationSetId", commandOptions.annotationSetId);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }


        TsvAnnotationParams tsvAnnotationParams = new TsvAnnotationParams();
        if (commandOptions.jsonDataModel) {
            RestResponse<Job> res = new RestResponse<>();
            res.setType(QueryType.VOID);
            PrintUtils.println(getObjectAsJSON(tsvAnnotationParams));
            return res;
        } else if (commandOptions.jsonFile != null) {
            tsvAnnotationParams = JacksonUtils.getDefaultObjectMapper()
                    .readValue(new java.io.File(commandOptions.jsonFile), TsvAnnotationParams.class);
        } else {
            tsvAnnotationParams.setContent(commandOptions.content);

        }
        return openCGAClient.getFileClient().loadAnnotationSets(commandOptions.variableSetId, commandOptions.path, tsvAnnotationParams, queryParams);
    }

    private RestResponse<File> create() throws Exception {

        logger.debug("Executing create in Files command line");

        FilesCommandOptions.CreateCommandOptions commandOptions = filesCommandOptions.createCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotNull("parents", commandOptions.parents);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }


        FileCreateParams fileCreateParams = new FileCreateParams();
        if (commandOptions.jsonDataModel) {
            RestResponse<File> res = new RestResponse<>();
            res.setType(QueryType.VOID);
            PrintUtils.println(getObjectAsJSON(fileCreateParams));
            return res;
        } else if (commandOptions.jsonFile != null) {
            fileCreateParams = JacksonUtils.getDefaultObjectMapper()
                    .readValue(new java.io.File(commandOptions.jsonFile), FileCreateParams.class);
        } else {
            // Generate beans for nested objects
            Software softwareParam = new Software();
            softwareParam.setName(commandOptions.softwareName);
            softwareParam.setVersion(commandOptions.softwareVersion);
            softwareParam.setRepository(commandOptions.softwareRepository);
            softwareParam.setCommit(commandOptions.softwareCommit);
            softwareParam.setWebsite(commandOptions.softwareWebsite);
            softwareParam.setParams(new HashMap<>(commandOptions.softwareParams));

            StatusParams statusParam = new StatusParams();
            statusParam.setId(commandOptions.statusId);
            statusParam.setName(commandOptions.statusName);
            statusParam.setDescription(commandOptions.statusDescription);

            //Set main body params
            fileCreateParams.setContent(commandOptions.content);
            fileCreateParams.setPath(commandOptions.path);
            fileCreateParams.setDescription(commandOptions.description);
            fileCreateParams.setType(commandOptions.type == null ? null : File.Type.valueOf(commandOptions.type));
            fileCreateParams.setFormat(commandOptions.format == null ? null : File.Format.valueOf(commandOptions.format));
            fileCreateParams.setBioformat(commandOptions.bioformat == null ? null : File.Bioformat.valueOf(commandOptions.bioformat));
            fileCreateParams.setSampleIds(splitWithTrim(commandOptions.sampleIds));
            fileCreateParams.setSoftware(softwareParam);
            fileCreateParams.setTags(splitWithTrim(commandOptions.tags));
            fileCreateParams.setJobId(commandOptions.jobId);
            fileCreateParams.setCreationDate(commandOptions.creationDate);
            fileCreateParams.setModificationDate(commandOptions.modificationDate);
            fileCreateParams.setStatus(statusParam);
            fileCreateParams.setAttributes(new HashMap<>(commandOptions.attributes));

        }
        return openCGAClient.getFileClient().create(fileCreateParams, queryParams);
    }

    private RestResponse<Object> distinct() throws Exception {

        logger.debug("Executing distinct in Files command line");

        FilesCommandOptions.DistinctCommandOptions commandOptions = filesCommandOptions.distinctCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("id", commandOptions.id);
        queryParams.putIfNotEmpty("uuid", commandOptions.uuid);
        queryParams.putIfNotEmpty("name", commandOptions.name);
        queryParams.putIfNotEmpty("path", commandOptions.path);
        queryParams.putIfNotEmpty("uri", commandOptions.uri);
        queryParams.putIfNotEmpty("type", commandOptions.type);
        queryParams.putIfNotEmpty("bioformat", commandOptions.bioformat);
        queryParams.putIfNotEmpty("format", commandOptions.format);
        queryParams.putIfNotNull("external", commandOptions.external);
        queryParams.putIfNotEmpty("status", commandOptions.status);
        queryParams.putIfNotEmpty("internalStatus", commandOptions.internalStatus);
        queryParams.putIfNotEmpty("internalVariantIndexStatus", commandOptions.internalVariantIndexStatus);
        queryParams.putIfNotEmpty("softwareName", commandOptions.softwareName);
        queryParams.putIfNotEmpty("directory", commandOptions.directory);
        queryParams.putIfNotEmpty("creationDate", commandOptions.creationDate);
        queryParams.putIfNotEmpty("modificationDate", commandOptions.modificationDate);
        queryParams.putIfNotEmpty("description", commandOptions.description);
        queryParams.putIfNotEmpty("tags", commandOptions.tags);
        queryParams.putIfNotEmpty("size", commandOptions.size);
        queryParams.putIfNotEmpty("sampleIds", commandOptions.sampleIds);
        queryParams.putIfNotEmpty("jobId", commandOptions.jobId);
        queryParams.putIfNotEmpty("annotation", commandOptions.annotation);
        queryParams.putIfNotEmpty("acl", commandOptions.acl);
        queryParams.putIfNotNull("deleted", commandOptions.deleted);
        queryParams.putIfNotEmpty("release", commandOptions.release);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().distinct(commandOptions.field, queryParams);
    }

    private RestResponse<Job> fetch() throws Exception {

        logger.debug("Executing fetch in Files command line");

        FilesCommandOptions.FetchCommandOptions commandOptions = filesCommandOptions.fetchCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("jobId", commandOptions.jobId);
        queryParams.putIfNotEmpty("jobDescription", commandOptions.jobDescription);
        queryParams.putIfNotEmpty("jobDependsOn", commandOptions.jobDependsOn);
        queryParams.putIfNotEmpty("jobTags", commandOptions.jobTags);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }


        FileFetch fileFetch = new FileFetch();
        if (commandOptions.jsonDataModel) {
            RestResponse<Job> res = new RestResponse<>();
            res.setType(QueryType.VOID);
            PrintUtils.println(getObjectAsJSON(fileFetch));
            return res;
        } else if (commandOptions.jsonFile != null) {
            fileFetch = JacksonUtils.getDefaultObjectMapper()
                    .readValue(new java.io.File(commandOptions.jsonFile), FileFetch.class);
        } else {
            fileFetch.setUrl(commandOptions.url);
            fileFetch.setPath(commandOptions.path);

        }
        return openCGAClient.getFileClient().fetch(fileFetch, queryParams);
    }

    private RestResponse<File> link() throws Exception {

        logger.debug("Executing link in Files command line");

        FilesCommandOptions.LinkCommandOptions commandOptions = filesCommandOptions.linkCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotNull("parents", commandOptions.parents);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }


        FileLinkParams fileLinkParams = new FileLinkParams();
        if (commandOptions.jsonDataModel) {
            RestResponse<File> res = new RestResponse<>();
            res.setType(QueryType.VOID);
            PrintUtils.println(getObjectAsJSON(fileLinkParams));
            return res;
        } else if (commandOptions.jsonFile != null) {
            fileLinkParams = JacksonUtils.getDefaultObjectMapper()
                    .readValue(new java.io.File(commandOptions.jsonFile), FileLinkParams.class);
        } else {
            // Generate beans for nested objects
            StatusParams statusParam = new StatusParams();
            statusParam.setId(commandOptions.statusId);
            statusParam.setName(commandOptions.statusName);
            statusParam.setDescription(commandOptions.statusDescription);

            FileLinkInternalParams internalParam = new FileLinkInternalParams();
            internalParam.setSampleMap(new HashMap<>(commandOptions.internalSampleMap));

            //Set main body params
            fileLinkParams.setUri(commandOptions.uri);
            fileLinkParams.setPath(commandOptions.path);
            fileLinkParams.setDescription(commandOptions.description);
            fileLinkParams.setCreationDate(commandOptions.creationDate);
            fileLinkParams.setModificationDate(commandOptions.modificationDate);
            //fileLinkParams.setRelatedFiles(commandOptions.relatedFiles); // Unsupported param. FIXME 
            fileLinkParams.setStatus(statusParam);
            fileLinkParams.setInternal(internalParam);

        }
        return openCGAClient.getFileClient().link(fileLinkParams, queryParams);
    }

    private RestResponse<Job> runLink() throws Exception {

        logger.debug("Executing runLink in Files command line");

        FilesCommandOptions.RunLinkCommandOptions commandOptions = filesCommandOptions.runLinkCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("jobId", commandOptions.jobId);
        queryParams.putIfNotEmpty("jobDependsOn", commandOptions.jobDependsOn);
        queryParams.putIfNotEmpty("jobDescription", commandOptions.jobDescription);
        queryParams.putIfNotEmpty("jobTags", commandOptions.jobTags);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }


        FileLinkToolParams fileLinkToolParams = new FileLinkToolParams();
        if (commandOptions.jsonDataModel) {
            RestResponse<Job> res = new RestResponse<>();
            res.setType(QueryType.VOID);
            PrintUtils.println(getObjectAsJSON(fileLinkToolParams));
            return res;
        } else if (commandOptions.jsonFile != null) {
            fileLinkToolParams = JacksonUtils.getDefaultObjectMapper()
                    .readValue(new java.io.File(commandOptions.jsonFile), FileLinkToolParams.class);
        } else {
            fileLinkToolParams.setUri(splitWithTrim(commandOptions.uri));
            fileLinkToolParams.setPath(commandOptions.path);
            fileLinkToolParams.setDescription(commandOptions.description);

            if (commandOptions.parents != null) {
                fileLinkToolParams.setParents(commandOptions.parents);
            }
        }
        return openCGAClient.getFileClient().runLink(fileLinkToolParams, queryParams);
    }

    private RestResponse<Job> runPostlink() throws Exception {

        logger.debug("Executing runPostlink in Files command line");

        FilesCommandOptions.RunPostlinkCommandOptions commandOptions = filesCommandOptions.runPostlinkCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("jobId", commandOptions.jobId);
        queryParams.putIfNotEmpty("jobDependsOn", commandOptions.jobDependsOn);
        queryParams.putIfNotEmpty("jobDescription", commandOptions.jobDescription);
        queryParams.putIfNotEmpty("jobTags", commandOptions.jobTags);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }


        PostLinkToolParams postLinkToolParams = new PostLinkToolParams();
        if (commandOptions.jsonDataModel) {
            RestResponse<Job> res = new RestResponse<>();
            res.setType(QueryType.VOID);
            PrintUtils.println(getObjectAsJSON(postLinkToolParams));
            return res;
        } else if (commandOptions.jsonFile != null) {
            postLinkToolParams = JacksonUtils.getDefaultObjectMapper()
                    .readValue(new java.io.File(commandOptions.jsonFile), PostLinkToolParams.class);
        } else {
            postLinkToolParams.setFiles(splitWithTrim(commandOptions.files));
            postLinkToolParams.setBatchSize(commandOptions.batchSize);

        }
        return openCGAClient.getFileClient().runPostlink(postLinkToolParams, queryParams);
    }

    private RestResponse<File> search() throws Exception {

        logger.debug("Executing search in Files command line");

        FilesCommandOptions.SearchCommandOptions commandOptions = filesCommandOptions.searchCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("include", commandOptions.include);
        queryParams.putIfNotEmpty("exclude", commandOptions.exclude);
        queryParams.putIfNotNull("limit", commandOptions.limit);
        queryParams.putIfNotNull("skip", commandOptions.skip);
        queryParams.putIfNotNull("count", commandOptions.count);
        queryParams.putIfNotNull("flattenAnnotations", commandOptions.flattenAnnotations);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("id", commandOptions.id);
        queryParams.putIfNotEmpty("uuid", commandOptions.uuid);
        queryParams.putIfNotEmpty("name", commandOptions.name);
        queryParams.putIfNotEmpty("path", commandOptions.path);
        queryParams.putIfNotEmpty("uri", commandOptions.uri);
        queryParams.putIfNotEmpty("type", commandOptions.type);
        queryParams.putIfNotEmpty("bioformat", commandOptions.bioformat);
        queryParams.putIfNotEmpty("format", commandOptions.format);
        queryParams.putIfNotNull("external", commandOptions.external);
        queryParams.putIfNotEmpty("status", commandOptions.status);
        queryParams.putIfNotEmpty("internalStatus", commandOptions.internalStatus);
        queryParams.putIfNotEmpty("internalVariantIndexStatus", commandOptions.internalVariantIndexStatus);
        queryParams.putIfNotEmpty("softwareName", commandOptions.softwareName);
        queryParams.putIfNotEmpty("directory", commandOptions.directory);
        queryParams.putIfNotEmpty("creationDate", commandOptions.creationDate);
        queryParams.putIfNotEmpty("modificationDate", commandOptions.modificationDate);
        queryParams.putIfNotEmpty("description", commandOptions.description);
        queryParams.putIfNotEmpty("tags", commandOptions.tags);
        queryParams.putIfNotEmpty("size", commandOptions.size);
        queryParams.putIfNotEmpty("sampleIds", commandOptions.sampleIds);
        queryParams.putIfNotEmpty("jobId", commandOptions.jobId);
        queryParams.putIfNotEmpty("annotation", commandOptions.annotation);
        queryParams.putIfNotEmpty("acl", commandOptions.acl);
        queryParams.putIfNotNull("deleted", commandOptions.deleted);
        queryParams.putIfNotEmpty("release", commandOptions.release);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().search(queryParams);
    }

    protected RestResponse<File> upload() throws Exception {

        logger.debug("Executing upload in Files command line");

        return super.upload();

    }

    private RestResponse<ObjectMap> acl() throws Exception {

        logger.debug("Executing acl in Files command line");

        FilesCommandOptions.AclCommandOptions commandOptions = filesCommandOptions.aclCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("member", commandOptions.member);
        queryParams.putIfNotNull("silent", commandOptions.silent);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().acl(commandOptions.files, queryParams);
    }

    private RestResponse<Job> delete() throws Exception {

        logger.debug("Executing delete in Files command line");

        FilesCommandOptions.DeleteCommandOptions commandOptions = filesCommandOptions.deleteCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotNull("skipTrash", commandOptions.skipTrash);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().delete(commandOptions.files, queryParams);
    }

    private RestResponse<File> info() throws Exception {

        logger.debug("Executing info in Files command line");

        FilesCommandOptions.InfoCommandOptions commandOptions = filesCommandOptions.infoCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("include", commandOptions.include);
        queryParams.putIfNotEmpty("exclude", commandOptions.exclude);
        queryParams.putIfNotNull("flattenAnnotations", commandOptions.flattenAnnotations);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotNull("deleted", commandOptions.deleted);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().info(commandOptions.files, queryParams);
    }

    private RestResponse<Job> unlink() throws Exception {

        logger.debug("Executing unlink in Files command line");

        FilesCommandOptions.UnlinkCommandOptions commandOptions = filesCommandOptions.unlinkCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().unlink(commandOptions.files, queryParams);
    }

    private RestResponse<File> update() throws Exception {

        logger.debug("Executing update in Files command line");

        FilesCommandOptions.UpdateCommandOptions commandOptions = filesCommandOptions.updateCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("include", commandOptions.include);
        queryParams.putIfNotEmpty("exclude", commandOptions.exclude);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotNull("sampleIdsAction", commandOptions.sampleIdsAction);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }


        FileUpdateParams fileUpdateParams = new FileUpdateParams();
        if (commandOptions.jsonDataModel) {
            RestResponse<File> res = new RestResponse<>();
            res.setType(QueryType.VOID);
            PrintUtils.println(getObjectAsJSON(fileUpdateParams));
            return res;
        } else if (commandOptions.jsonFile != null) {
            fileUpdateParams = JacksonUtils.getDefaultObjectMapper()
                    .readValue(new java.io.File(commandOptions.jsonFile), FileUpdateParams.class);
        } else {
            // Generate beans for nested objects
            Software softwareParam = new Software();
            softwareParam.setName(commandOptions.softwareName);
            softwareParam.setVersion(commandOptions.softwareVersion);
            softwareParam.setRepository(commandOptions.softwareRepository);
            softwareParam.setCommit(commandOptions.softwareCommit);
            softwareParam.setWebsite(commandOptions.softwareWebsite);
            softwareParam.setParams(new HashMap<>(commandOptions.softwareParams));

            FileExperiment experimentParam = new FileExperiment();
            experimentParam.setTechnology(commandOptions.experimentTechnology == null ? null : FileExperiment.Technology.valueOf(commandOptions.experimentTechnology));
            experimentParam.setMethod(commandOptions.experimentMethod == null ? null : FileExperiment.Method.valueOf(commandOptions.experimentMethod));
            experimentParam.setNucleicAcidType(commandOptions.experimentNucleicAcidType == null ? null : FileExperiment.NucleicAcidType.valueOf(commandOptions.experimentNucleicAcidType));
            experimentParam.setManufacturer(commandOptions.experimentManufacturer);
            experimentParam.setPlatform(commandOptions.experimentPlatform);
            experimentParam.setLibrary(commandOptions.experimentLibrary);
            experimentParam.setDate(commandOptions.experimentDate);
            experimentParam.setCenter(commandOptions.experimentCenter);
            experimentParam.setLab(commandOptions.experimentLab);
            experimentParam.setResponsible(commandOptions.experimentResponsible);
            experimentParam.setDescription(commandOptions.experimentDescription);
            experimentParam.setAttributes(new HashMap<>(commandOptions.experimentAttributes));

            SmallFileInternal internalParam = new SmallFileInternal();
            //internalParam.setStatus(commandOptions.internalStatus);  // Unsupported param. FIXME
            //internalParam.setMissingSamples(commandOptions.internalMissingSamples);  // Unsupported param. FIXME

            StatusParams statusParam = new StatusParams();
            statusParam.setId(commandOptions.statusId);
            statusParam.setName(commandOptions.statusName);
            statusParam.setDescription(commandOptions.statusDescription);

            FileQualityControl qualityControlParam = new FileQualityControl();
            //qualityControlParam.setVariant(commandOptions.qualityControlVariant);  // Unsupported param. FIXME
            //qualityControlParam.setAlignment(commandOptions.qualityControlAlignment);  // Unsupported param. FIXME
            //qualityControlParam.setCoverage(commandOptions.qualityControlCoverage);  // Unsupported param. FIXME
            //qualityControlParam.setComments(commandOptions.qualityControlComments);  // Unsupported param. FIXME
            qualityControlParam.setFiles(splitWithTrim(commandOptions.qualityControlFiles));

            //Set main body params
            fileUpdateParams.setName(commandOptions.name);
            fileUpdateParams.setDescription(commandOptions.description);
            fileUpdateParams.setCreationDate(commandOptions.creationDate);
            fileUpdateParams.setModificationDate(commandOptions.modificationDate);
            fileUpdateParams.setSampleIds(splitWithTrim(commandOptions.sampleIds));
            fileUpdateParams.setChecksum(commandOptions.checksum);
            fileUpdateParams.setFormat(commandOptions.format == null ? null : File.Format.valueOf(commandOptions.format));
            fileUpdateParams.setBioformat(commandOptions.bioformat == null ? null : File.Bioformat.valueOf(commandOptions.bioformat));
            fileUpdateParams.setSoftware(softwareParam);
            fileUpdateParams.setExperiment(experimentParam);
            fileUpdateParams.setTags(splitWithTrim(commandOptions.tags));
            fileUpdateParams.setInternal(internalParam);
            //fileUpdateParams.setRelatedFiles(commandOptions.relatedFiles); // Unsupported param. FIXME 
            fileUpdateParams.setSize(commandOptions.size);
            fileUpdateParams.setStatus(statusParam);
            //fileUpdateParams.setAnnotationSets(commandOptions.annotationSets); // Unsupported param. FIXME 
            fileUpdateParams.setQualityControl(qualityControlParam);
            fileUpdateParams.setStats(new HashMap<>(commandOptions.stats));
            fileUpdateParams.setAttributes(new HashMap<>(commandOptions.attributes));

        }
        return openCGAClient.getFileClient().update(commandOptions.files, fileUpdateParams, queryParams);
    }

    private RestResponse<File> updateAnnotationSetsAnnotations() throws Exception {

        logger.debug("Executing updateAnnotationSetsAnnotations in Files command line");

        FilesCommandOptions.UpdateAnnotationSetsAnnotationsCommandOptions commandOptions = filesCommandOptions.updateAnnotationSetsAnnotationsCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotNull("action", commandOptions.action);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }


        ObjectMap objectMap = new ObjectMap();
        if (commandOptions.jsonDataModel) {
            RestResponse<File> res = new RestResponse<>();
            res.setType(QueryType.VOID);
            PrintUtils.println(getObjectAsJSON(objectMap));
            return res;
        } else if (commandOptions.jsonFile != null) {
            objectMap = JacksonUtils.getDefaultObjectMapper()
                    .readValue(new java.io.File(commandOptions.jsonFile), ObjectMap.class);
        }
        return openCGAClient.getFileClient().updateAnnotationSetsAnnotations(commandOptions.file, commandOptions.annotationSet, objectMap, queryParams);
    }

    private RestResponse<DataInputStream> download() throws Exception {

        logger.debug("Executing download in Files command line");

        FilesCommandOptions.DownloadCommandOptions commandOptions = filesCommandOptions.downloadCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().download(commandOptions.file, queryParams);
    }

    private RestResponse<FileContent> grep() throws Exception {

        logger.debug("Executing grep in Files command line");

        FilesCommandOptions.GrepCommandOptions commandOptions = filesCommandOptions.grepCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("pattern", commandOptions.pattern);
        queryParams.putIfNotNull("ignoreCase", commandOptions.ignoreCase);
        queryParams.putIfNotNull("maxCount", commandOptions.maxCount);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().grep(commandOptions.file, queryParams);
    }

    private RestResponse<FileContent> head() throws Exception {

        logger.debug("Executing head in Files command line");

        FilesCommandOptions.HeadCommandOptions commandOptions = filesCommandOptions.headCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotNull("offset", commandOptions.offset);
        queryParams.putIfNotNull("lines", commandOptions.lines);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().head(commandOptions.file, queryParams);
    }

    private RestResponse<FileContent> image() throws Exception {

        logger.debug("Executing image in Files command line");

        FilesCommandOptions.ImageCommandOptions commandOptions = filesCommandOptions.imageCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().image(commandOptions.file, queryParams);
    }

    private RestResponse<File> refresh() throws Exception {

        logger.debug("Executing refresh in Files command line");

        FilesCommandOptions.RefreshCommandOptions commandOptions = filesCommandOptions.refreshCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().refresh(commandOptions.file, queryParams);
    }

    private RestResponse<FileContent> tail() throws Exception {

        logger.debug("Executing tail in Files command line");

        FilesCommandOptions.TailCommandOptions commandOptions = filesCommandOptions.tailCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotNull("lines", commandOptions.lines);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().tail(commandOptions.file, queryParams);
    }

    private RestResponse<File> list() throws Exception {

        logger.debug("Executing list in Files command line");

        FilesCommandOptions.ListCommandOptions commandOptions = filesCommandOptions.listCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("include", commandOptions.include);
        queryParams.putIfNotEmpty("exclude", commandOptions.exclude);
        queryParams.putIfNotNull("limit", commandOptions.limit);
        queryParams.putIfNotNull("skip", commandOptions.skip);
        queryParams.putIfNotNull("count", commandOptions.count);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().list(commandOptions.folder, queryParams);
    }

    private RestResponse<FileTree> tree() throws Exception {

        logger.debug("Executing tree in Files command line");

        FilesCommandOptions.TreeCommandOptions commandOptions = filesCommandOptions.treeCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("include", commandOptions.include);
        queryParams.putIfNotEmpty("exclude", commandOptions.exclude);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotNull("maxDepth", commandOptions.maxDepth);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return openCGAClient.getFileClient().tree(commandOptions.folder, queryParams);
    }
}