
# WARNING: AUTOGENERATED CODE
#
#    This code was generated by a tool.
#    Autogenerated on: 2023-10-20
#    
#    Manual changes to this file may cause unexpected behavior in your application.
#    Manual changes to this file will be overwritten if the code is regenerated.


# ##############################################################################
#' CvdbClient methods
#' @include AllClasses.R
#' @include AllGenerics.R
#' @include commons.R

#' @description This function implements the OpenCGA calls for managing Cvdb.

#' The following table summarises the available *actions* for this client:
#'
#' | endpointName | Endpoint WS | parameters accepted |
#' | -- | :-- | --: |
#' | indexCase | /{apiVersion}/cvdb/case/index | study, clinicalAnalysisId, overwrite |
#' | runCaseIndex | /{apiVersion}/cvdb/case/index/run | study, jobId, jobDescription, jobDependsOn, jobTags, body[*] |
#' | queryCase | /{apiVersion}/cvdb/case/query | projectId, include, limit, caId, caType, caDisorderId, caFilename, caProbandId, caFamilyId, caFamilyPhenotypeName, caFamilyMemberId, ciId, ciPanelId, ciAnalystId, ciAnalystName, ciAnalystEmail, ciAnalystAssignedBy, ciMethodName, ciMethodVersion, ciMethodCommit, ciStatusId, ciStatusName, variantId |
#' | queryClinicalVariant | /{apiVersion}/cvdb/clinicalVariant/query | projectId, include, limit, caId, caType, caDisorderId, caFilename, caProbandId, caFamilyId, caFamilyPhenotypeName, caFamilyMemberId, ciId, ciPanelId, ciAnalystId, ciAnalystName, ciAnalystEmail, ciAnalystAssignedBy, ciMethodName, ciMethodVersion, ciMethodCommit, ciStatusId, ciStatusName, variantId |
#' | queryClinicalVariantEvidence | /{apiVersion}/cvdb/clinicalVariantEvidence/query | projectId, include, limit, caId, caType, caDisorderId, caFilename, caProbandId, caFamilyId, caFamilyPhenotypeName, caFamilyMemberId, ciId, ciPanelId, ciAnalystId, ciAnalystName, ciAnalystEmail, ciAnalystAssignedBy, ciMethodName, ciMethodVersion, ciMethodCommit, ciStatusId, ciStatusName, variantId |
#' | queryInterpretation | /{apiVersion}/cvdb/interpretation/query | projectId, include, limit, caId, caType, caDisorderId, caFilename, caProbandId, caFamilyId, caFamilyPhenotypeName, caFamilyMemberId, ciId, ciPanelId, ciAnalystId, ciAnalystName, ciAnalystEmail, ciAnalystAssignedBy, ciMethodName, ciMethodVersion, ciMethodCommit, ciStatusId, ciStatusName, variantId |
#' | info | /{apiVersion}/cvdb/{caseId}/info | include, exclude, includeIndividual, flattenAnnotations, caseId[*], study, version, deleted |
#'
#' @md
#' @seealso \url{http://docs.opencb.org/display/opencga/Using+OpenCGA} and the RESTful API documentation
#' \url{http://bioinfo.hpc.cam.ac.uk/opencga-prod/webservices/}
#' [*]: Required parameter
#' @export

setMethod("cvdbClient", "OpencgaR", function(OpencgaR, caseId, endpointName, params=NULL, ...) {
    switch(endpointName,

        #' @section Endpoint /{apiVersion}/cvdb/case/index:
        #' Index clinical analyses into CVDB.
        #' @param study Study [[user@]project:]study where study and project can be either the ID or UUID.
        #' @param clinicalAnalysisId Clinical analysis ID (or list of clinical analysis IDs separated by commas).
        #' @param overwrite Overwrite clinical analysis when CVDB indexing.
        indexCase=fetchOpenCGA(object=OpencgaR, category="cvdb", categoryId=NULL, subcategory="case",
                subcategoryId=NULL, action="index", params=params, httpMethod="GET", as.queryParam=NULL, ...),

        #' @section Endpoint /{apiVersion}/cvdb/case/index/run:
        #' Index all clinical analyses of a OpenCGA project into CVDB.
        #' @param study Study [[user@]project:]study where study and project can be either the ID or UUID.
        #' @param jobId Job ID. It must be a unique string within the study. An ID will be autogenerated automatically if not provided.
        #' @param jobDescription Job description.
        #' @param jobDependsOn Comma separated list of existing job IDs the job will depend on.
        #' @param jobTags Job tags.
        #' @param data Parameters to index clinical analysis into CVDB.
        runCaseIndex=fetchOpenCGA(object=OpencgaR, category="cvdb", categoryId=NULL, subcategory="case/index",
                subcategoryId=NULL, action="run", params=params, httpMethod="POST", as.queryParam=NULL, ...),

        #' @section Endpoint /{apiVersion}/cvdb/case/query:
        #' Filter and fetch clinical analyses from CVDB.
        #' @param projectId Project ID.
        #' @param include Fields included in the response, whole JSON path must be provided.
        #' @param limit Number of results to be returned.
        #' @param caId Clinical analysis ID (or list of IDs separated by commas).
        #' @param caType Clinical analysis type (or list of types separated by commas).
        #' @param caDisorderId Clinical analysis disorder ID (or list of IDs separated by commas).
        #' @param caFilename Clinical analysis filename (or list of filenames separated by commas).
        #' @param caProbandId Clinical analysis proband ID (or list of IDs separated by commas).
        #' @param caFamilyId Clinical analysis family ID (or list of IDs separated by commas).
        #' @param caFamilyPhenotypeName Clinical analysis family phenotype names (or list of names separated by commas).
        #' @param caFamilyMemberId Clinical analysis family member ID (or list of IDs separated by commas).
        #' @param ciId Clinical interpretation ID (or list of IDs separated by commas).
        #' @param ciPanelId Clinical interpretation panel ID or name (or list of IDs or names separated by commas).
        #' @param ciAnalystId Clinical interpretation analyst ID (or list of IDs separated by commas).
        #' @param ciAnalystName Clinical interpretation analyst name (or list of names separated by commas).
        #' @param ciAnalystEmail Clinical interpretation analyst e-mail (or list of e-mails separated by commas).
        #' @param ciAnalystAssignedBy Clinical interpretation analyst assignee name (or list of names separated by commas).
        #' @param ciMethodName Clinical interpretation method name (or list of names separated by commas).
        #' @param ciMethodVersion Clinical interpretation method version (or list of versions separated by commas).
        #' @param ciMethodCommit Clinical interpretation method commit (or list of commits separated by commas).
        #' @param ciStatusId Clinical interpretation status ID (or list of IDs separated by commas).
        #' @param ciStatusName Clinical interpretation status name (or list of names separated by commas).
        #' @param variantId Variant ID (or list of variant IDs separated by commas), e.g.: 6:31356248:G:C,X:53196017:G:A.
        queryCase=fetchOpenCGA(object=OpencgaR, category="cvdb", categoryId=NULL, subcategory="case",
                subcategoryId=NULL, action="query", params=params, httpMethod="GET", as.queryParam=NULL, ...),

        #' @section Endpoint /{apiVersion}/cvdb/clinicalVariant/query:
        #' Filter and fetch clinical variants from CVDB.
        #' @param projectId Project ID.
        #' @param include Fields included in the response, whole JSON path must be provided.
        #' @param limit Number of results to be returned.
        #' @param caId Clinical analysis ID (or list of IDs separated by commas).
        #' @param caType Clinical analysis type (or list of types separated by commas).
        #' @param caDisorderId Clinical analysis disorder ID (or list of IDs separated by commas).
        #' @param caFilename Clinical analysis filename (or list of filenames separated by commas).
        #' @param caProbandId Clinical analysis proband ID (or list of IDs separated by commas).
        #' @param caFamilyId Clinical analysis family ID (or list of IDs separated by commas).
        #' @param caFamilyPhenotypeName Clinical analysis family phenotype names (or list of names separated by commas).
        #' @param caFamilyMemberId Clinical analysis family member ID (or list of IDs separated by commas).
        #' @param ciId Clinical interpretation ID (or list of IDs separated by commas).
        #' @param ciPanelId Clinical interpretation panel ID or name (or list of IDs or names separated by commas).
        #' @param ciAnalystId Clinical interpretation analyst ID (or list of IDs separated by commas).
        #' @param ciAnalystName Clinical interpretation analyst name (or list of names separated by commas).
        #' @param ciAnalystEmail Clinical interpretation analyst e-mail (or list of e-mails separated by commas).
        #' @param ciAnalystAssignedBy Clinical interpretation analyst assignee name (or list of names separated by commas).
        #' @param ciMethodName Clinical interpretation method name (or list of names separated by commas).
        #' @param ciMethodVersion Clinical interpretation method version (or list of versions separated by commas).
        #' @param ciMethodCommit Clinical interpretation method commit (or list of commits separated by commas).
        #' @param ciStatusId Clinical interpretation status ID (or list of IDs separated by commas).
        #' @param ciStatusName Clinical interpretation status name (or list of names separated by commas).
        #' @param variantId Variant ID (or list of variant IDs separated by commas), e.g.: 6:31356248:G:C,X:53196017:G:A.
        queryClinicalVariant=fetchOpenCGA(object=OpencgaR, category="cvdb", categoryId=NULL,
                subcategory="clinicalVariant", subcategoryId=NULL, action="query", params=params, httpMethod="GET",
                as.queryParam=NULL, ...),

        #' @section Endpoint /{apiVersion}/cvdb/clinicalVariantEvidence/query:
        #' Filter and fetch clinical variant evidences from CVDB.
        #' @param projectId Project ID.
        #' @param include Fields included in the response, whole JSON path must be provided.
        #' @param limit Number of results to be returned.
        #' @param caId Clinical analysis ID (or list of IDs separated by commas).
        #' @param caType Clinical analysis type (or list of types separated by commas).
        #' @param caDisorderId Clinical analysis disorder ID (or list of IDs separated by commas).
        #' @param caFilename Clinical analysis filename (or list of filenames separated by commas).
        #' @param caProbandId Clinical analysis proband ID (or list of IDs separated by commas).
        #' @param caFamilyId Clinical analysis family ID (or list of IDs separated by commas).
        #' @param caFamilyPhenotypeName Clinical analysis family phenotype names (or list of names separated by commas).
        #' @param caFamilyMemberId Clinical analysis family member ID (or list of IDs separated by commas).
        #' @param ciId Clinical interpretation ID (or list of IDs separated by commas).
        #' @param ciPanelId Clinical interpretation panel ID or name (or list of IDs or names separated by commas).
        #' @param ciAnalystId Clinical interpretation analyst ID (or list of IDs separated by commas).
        #' @param ciAnalystName Clinical interpretation analyst name (or list of names separated by commas).
        #' @param ciAnalystEmail Clinical interpretation analyst e-mail (or list of e-mails separated by commas).
        #' @param ciAnalystAssignedBy Clinical interpretation analyst assignee name (or list of names separated by commas).
        #' @param ciMethodName Clinical interpretation method name (or list of names separated by commas).
        #' @param ciMethodVersion Clinical interpretation method version (or list of versions separated by commas).
        #' @param ciMethodCommit Clinical interpretation method commit (or list of commits separated by commas).
        #' @param ciStatusId Clinical interpretation status ID (or list of IDs separated by commas).
        #' @param ciStatusName Clinical interpretation status name (or list of names separated by commas).
        #' @param variantId Variant ID (or list of variant IDs separated by commas), e.g.: 6:31356248:G:C,X:53196017:G:A.
        queryClinicalVariantEvidence=fetchOpenCGA(object=OpencgaR, category="cvdb", categoryId=NULL,
                subcategory="clinicalVariantEvidence", subcategoryId=NULL, action="query", params=params,
                httpMethod="GET", as.queryParam=NULL, ...),

        #' @section Endpoint /{apiVersion}/cvdb/interpretation/query:
        #' Filter and fetch clinical interpretations from CVDB.
        #' @param projectId Project ID.
        #' @param include Fields included in the response, whole JSON path must be provided.
        #' @param limit Number of results to be returned.
        #' @param caId Clinical analysis ID (or list of IDs separated by commas).
        #' @param caType Clinical analysis type (or list of types separated by commas).
        #' @param caDisorderId Clinical analysis disorder ID (or list of IDs separated by commas).
        #' @param caFilename Clinical analysis filename (or list of filenames separated by commas).
        #' @param caProbandId Clinical analysis proband ID (or list of IDs separated by commas).
        #' @param caFamilyId Clinical analysis family ID (or list of IDs separated by commas).
        #' @param caFamilyPhenotypeName Clinical analysis family phenotype names (or list of names separated by commas).
        #' @param caFamilyMemberId Clinical analysis family member ID (or list of IDs separated by commas).
        #' @param ciId Clinical interpretation ID (or list of IDs separated by commas).
        #' @param ciPanelId Clinical interpretation panel ID or name (or list of IDs or names separated by commas).
        #' @param ciAnalystId Clinical interpretation analyst ID (or list of IDs separated by commas).
        #' @param ciAnalystName Clinical interpretation analyst name (or list of names separated by commas).
        #' @param ciAnalystEmail Clinical interpretation analyst e-mail (or list of e-mails separated by commas).
        #' @param ciAnalystAssignedBy Clinical interpretation analyst assignee name (or list of names separated by commas).
        #' @param ciMethodName Clinical interpretation method name (or list of names separated by commas).
        #' @param ciMethodVersion Clinical interpretation method version (or list of versions separated by commas).
        #' @param ciMethodCommit Clinical interpretation method commit (or list of commits separated by commas).
        #' @param ciStatusId Clinical interpretation status ID (or list of IDs separated by commas).
        #' @param ciStatusName Clinical interpretation status name (or list of names separated by commas).
        #' @param variantId Variant ID (or list of variant IDs separated by commas), e.g.: 6:31356248:G:C,X:53196017:G:A.
        queryInterpretation=fetchOpenCGA(object=OpencgaR, category="cvdb", categoryId=NULL,
                subcategory="interpretation", subcategoryId=NULL, action="query", params=params, httpMethod="GET",
                as.queryParam=NULL, ...),

        #' @section Endpoint /{apiVersion}/cvdb/{caseId}/info:
        #' Get sample information.
        #' @param include Fields included in the response, whole JSON path must be provided.
        #' @param exclude Fields excluded in the response, whole JSON path must be provided.
        #' @param includeIndividual Include Individual object as an attribute.
        #' @param flattenAnnotations Flatten the annotations?.
        #' @param caseId Comma separated list sample IDs or UUIDs up to a maximum of 100.
        #' @param study Study [[user@]project:]study where study and project can be either the ID or UUID.
        #' @param version Comma separated list of sample versions. 'all' to get all the sample versions. Not supported if multiple sample ids are provided.
        #' @param deleted Boolean to retrieve deleted entries.
        info=fetchOpenCGA(object=OpencgaR, category="cvdb", categoryId=caseId, subcategory=NULL, subcategoryId=NULL,
                action="info", params=params, httpMethod="GET", as.queryParam=NULL, ...),
    )
})