package com.zettagenomics.opencga.enterprise.core.models.audit;

public enum AuditAction {

    CREATE_FEDERATION_CLIENT,
    CREATE_FEDERATION_SERVER,
    SYNCHRONIZE_FEDERATION_CLIENT,
    UPDATE_FEDERATION_CLIENT,
    UPDATE_FEDERATION_SERVER,
    RESET_FEDERATION_CLIENT_CREDENTIALS,
    RESET_FEDERATION_SECURITY_KEY,
    DELETE_FEDERATION_CLIENT,
    DELETE_FEDERATION_SERVER,
    FEDERATION_REDIRECT,
    FEDERATION_SHARE,
    FEDERATION_SHOW_USERS,
}
