package com.zettagenomics.opencga.enterprise.app.cli.main.executors;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.zettagenomics.opencga.enterprise.app.cli.main.executors.EnterpriseOpencgaCommandExecutor;
import com.zettagenomics.opencga.enterprise.app.cli.main.options.CVDBCommandOptions;
import com.zettagenomics.opencga.enterprise.cvdb.tasks.params.CvdbIndexTaskParams;
import java.util.HashMap;
import java.util.List;
import org.opencb.biodata.models.clinical.interpretation.ClinicalVariant;
import org.opencb.biodata.models.clinical.interpretation.ClinicalVariantEvidence;
import org.opencb.biodata.models.clinical.interpretation.stats.ClinicalVariantSummaryStats;
import org.opencb.commons.datastore.core.FacetField;
import org.opencb.commons.datastore.core.ObjectMap;
import org.opencb.commons.utils.PrintUtils;
import org.opencb.opencga.app.cli.main.*;
import org.opencb.opencga.catalog.exceptions.CatalogAuthenticationException;
import org.opencb.opencga.client.exceptions.ClientException;
import org.opencb.opencga.core.common.JacksonUtils;
import org.opencb.opencga.core.models.clinical.ClinicalAnalysis;
import org.opencb.opencga.core.models.clinical.Interpretation;
import org.opencb.opencga.core.models.job.Job;
import org.opencb.opencga.core.response.QueryType;
import org.opencb.opencga.core.response.RestResponse;


/*
* WARNING: AUTOGENERATED CODE
*
* This code was generated by a tool.
*
* Manual changes to this file may cause unexpected behavior in your application.
* Manual changes to this file will be overwritten if the code is regenerated.
*  
*/
/**
 * This class contains methods for the CVDB command line.
 *    PATH: /{apiVersion}/analysis/cvdb
 */
public class CVDBCommandExecutor extends com.zettagenomics.opencga.enterprise.app.cli.main.executors.EnterpriseOpencgaCommandExecutor {

    public String categoryName = "cvdb";
    public CVDBCommandOptions cVDBCommandOptions;

    public CVDBCommandExecutor(CVDBCommandOptions cVDBCommandOptions) throws CatalogAuthenticationException {
        super(cVDBCommandOptions.commonCommandOptions);
        this.cVDBCommandOptions = cVDBCommandOptions;
    }

    @Override
    public void execute() throws Exception {

        logger.debug("Executing CVDB command line");

        String subCommandString = getParsedSubCommand(cVDBCommandOptions.jCommander);

        RestResponse queryResponse = null;

        switch (subCommandString) {
            case "case-aggregate":
                queryResponse = aggregateCase();
                break;
            case "case-query":
                queryResponse = queryCase();
                break;
            case "clinical-variant-aggregate":
                queryResponse = aggregateClinicalVariant();
                break;
            case "clinical-variant-query":
                queryResponse = queryClinicalVariant();
                break;
            case "clinical-variant-stats":
                queryResponse = statsClinicalVariant();
                break;
            case "index-run":
                queryResponse = runIndex();
                break;
            case "interpretation-aggregate":
                queryResponse = aggregateInterpretation();
                break;
            case "interpretation-query":
                queryResponse = queryInterpretation();
                break;
            case "variant-evidence-aggregate":
                queryResponse = aggregateVariantEvidence();
                break;
            case "variant-evidence-query":
                queryResponse = queryVariantEvidence();
                break;
            default:
                logger.error("Subcommand not valid");
                break;
        }

        createOutput(queryResponse);

    }

    private RestResponse<FacetField> aggregateCase() throws Exception {
        logger.debug("Executing aggregateCase in CVDB command line");

        CVDBCommandOptions.AggregateCaseCommandOptions commandOptions = cVDBCommandOptions.aggregateCaseCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("project", commandOptions.project);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("caId", commandOptions.caId);
        queryParams.putIfNotEmpty("caDescription", commandOptions.caDescription);
        queryParams.putIfNotEmpty("caType", commandOptions.caType);
        queryParams.putIfNotEmpty("caDisorderId", commandOptions.caDisorderId);
        queryParams.putIfNotEmpty("caFilename", commandOptions.caFilename);
        queryParams.putIfNotEmpty("caProbandId", commandOptions.caProbandId);
        queryParams.putIfNotEmpty("caProbandDisorderId", commandOptions.caProbandDisorderId);
        queryParams.putIfNotEmpty("caProbandPhenotypeName", commandOptions.caProbandPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyId", commandOptions.caFamilyId);
        queryParams.putIfNotEmpty("caFamilyPhenotypeName", commandOptions.caFamilyPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyMemberId", commandOptions.caFamilyMemberId);
        queryParams.putIfNotEmpty("caReport", commandOptions.caReport);
        queryParams.putIfNotEmpty("caStatus", commandOptions.caStatus);
        queryParams.putIfNotNull("caLocked", commandOptions.caLocked);
        queryParams.putIfNotEmpty("ciId", commandOptions.ciId);
        queryParams.putIfNotNull("ciPrimary", commandOptions.ciPrimary);
        queryParams.putIfNotEmpty("ciDescription", commandOptions.ciDescription);
        queryParams.putIfNotEmpty("ciPanelId", commandOptions.ciPanelId);
        queryParams.putIfNotEmpty("ciAnalystId", commandOptions.ciAnalystId);
        queryParams.putIfNotEmpty("ciAnalystName", commandOptions.ciAnalystName);
        queryParams.putIfNotEmpty("ciAnalystEmail", commandOptions.ciAnalystEmail);
        queryParams.putIfNotEmpty("ciAnalystAssignedBy", commandOptions.ciAnalystAssignedBy);
        queryParams.putIfNotEmpty("ciAnalystDate", commandOptions.ciAnalystDate);
        queryParams.putIfNotEmpty("ciMethodName", commandOptions.ciMethodName);
        queryParams.putIfNotEmpty("ciMethodVersion", commandOptions.ciMethodVersion);
        queryParams.putIfNotEmpty("ciMethodCommit", commandOptions.ciMethodCommit);
        queryParams.putIfNotEmpty("ciMethodDependencies", commandOptions.ciMethodDependencies);
        queryParams.putIfNotEmpty("ciComments", commandOptions.ciComments);
        queryParams.putIfNotNull("ciLocked", commandOptions.ciLocked);
        queryParams.putIfNotEmpty("ciStatusId", commandOptions.ciStatusId);
        queryParams.putIfNotEmpty("ciStatusName", commandOptions.ciStatusName);
        queryParams.putIfNotEmpty("ciStatusDescription", commandOptions.ciStatusDescription);
        queryParams.putIfNotEmpty("ciStatusDate", commandOptions.ciStatusDate);
        queryParams.putIfNotEmpty("ciCreationDate", commandOptions.ciCreationDate);
        queryParams.putIfNotEmpty("ciModificationDate", commandOptions.ciModificationDate);
        queryParams.putIfNotNull("ciVersion", commandOptions.ciVersion);
        queryParams.putIfNotEmpty("cvId", commandOptions.cvId);
        queryParams.putIfNotEmpty("cvVariantId", commandOptions.cvVariantId);
        queryParams.putIfNotNull("cvPrimaryFinding", commandOptions.cvPrimaryFinding);
        queryParams.putIfNotNull("cvPrimaryInterpretation", commandOptions.cvPrimaryInterpretation);
        queryParams.putIfNotEmpty("cvComments", commandOptions.cvComments);
        queryParams.putIfNotEmpty("cvDiscussionAuthor", commandOptions.cvDiscussionAuthor);
        queryParams.putIfNotEmpty("cvDiscussionDate", commandOptions.cvDiscussionDate);
        queryParams.putIfNotEmpty("cvDiscussionText", commandOptions.cvDiscussionText);
        queryParams.putIfNotEmpty("cvConfidenceValue", commandOptions.cvConfidenceValue);
        queryParams.putIfNotEmpty("cvConfidenceAuthor", commandOptions.cvConfidenceAuthor);
        queryParams.putIfNotEmpty("cvConfidenceDate", commandOptions.cvConfidenceDate);
        queryParams.putIfNotEmpty("cvTag", commandOptions.cvTag);
        queryParams.putIfNotEmpty("cvStatus", commandOptions.cvStatus);
        queryParams.putIfNotEmpty("cvRegion", commandOptions.cvRegion);
        queryParams.putIfNotEmpty("cvBiotype", commandOptions.cvBiotype);
        queryParams.putIfNotEmpty("cvCt", commandOptions.cvCt);
        queryParams.putIfNotEmpty("cvTranscriptFlag", commandOptions.cvTranscriptFlag);
        queryParams.putIfNotEmpty("cvGene", commandOptions.cvGene);
        queryParams.putIfNotEmpty("cvXref", commandOptions.cvXref);
        queryParams.putIfNotEmpty("cvAnnotRoleInCancerGenes", commandOptions.cvAnnotRoleInCancerGenes);
        queryParams.putIfNotEmpty("cvType", commandOptions.cvType);
        queryParams.putIfNotEmpty("cvProteinSubstitution", commandOptions.cvProteinSubstitution);
        queryParams.putIfNotEmpty("cvConservation", commandOptions.cvConservation);
        queryParams.putIfNotEmpty("cvFunctionalScore", commandOptions.cvFunctionalScore);
        queryParams.putIfNotEmpty("cvPopulationFrequencyAlt", commandOptions.cvPopulationFrequencyAlt);
        queryParams.putIfNotEmpty("cvPopulationFrequencyMaf", commandOptions.cvPopulationFrequencyMaf);
        queryParams.putIfNotEmpty("cvPopulationFrequencyRef", commandOptions.cvPopulationFrequencyRef);
        queryParams.putIfNotEmpty("cvCohortStatsAlt", commandOptions.cvCohortStatsAlt);
        queryParams.putIfNotEmpty("cvCohortStatsMaf", commandOptions.cvCohortStatsMaf);
        queryParams.putIfNotEmpty("cvCohortStatsRef", commandOptions.cvCohortStatsRef);
        queryParams.putIfNotEmpty("cvCohortStatsPass", commandOptions.cvCohortStatsPass);
        queryParams.putIfNotEmpty("cvScore", commandOptions.cvScore);
        queryParams.putIfNotEmpty("cvAnnotGoGenes", commandOptions.cvAnnotGoGenes);
        queryParams.putIfNotEmpty("cvAnnotExpressionGenes", commandOptions.cvAnnotExpressionGenes);
        queryParams.putIfNotEmpty("cvGeneTraitId", commandOptions.cvGeneTraitId);
        queryParams.putIfNotEmpty("cvTrait", commandOptions.cvTrait);
        queryParams.putIfNotEmpty("cvProteinKeyword", commandOptions.cvProteinKeyword);
        queryParams.putIfNotEmpty("cveVariantId", commandOptions.cveVariantId);
        queryParams.putIfNotNull("cvePrimaryFinding", commandOptions.cvePrimaryFinding);
        queryParams.putIfNotNull("cvePrimaryInterpretation", commandOptions.cvePrimaryInterpretation);
        queryParams.putIfNotEmpty("cvePhenotypeName", commandOptions.cvePhenotypeName);
        queryParams.putIfNotEmpty("cveGeneName", commandOptions.cveGeneName);
        queryParams.putIfNotEmpty("cveTranscriptId", commandOptions.cveTranscriptId);
        queryParams.putIfNotEmpty("cveSoTermName", commandOptions.cveSoTermName);
        queryParams.putIfNotEmpty("cveXrefId", commandOptions.cveXrefId);
        queryParams.putIfNotEmpty("cvePanelId", commandOptions.cvePanelId);
        queryParams.putIfNotEmpty("cveMoi", commandOptions.cveMoi);
        queryParams.putIfNotEmpty("cvePenetrance", commandOptions.cvePenetrance);
        queryParams.putIfNotEmpty("cveAcmg", commandOptions.cveAcmg);
        queryParams.putIfNotEmpty("cveTier", commandOptions.cveTier);
        queryParams.putIfNotEmpty("cveClinicalSignificance", commandOptions.cveClinicalSignificance);
        queryParams.putIfNotEmpty("cveDrugResponse", commandOptions.cveDrugResponse);
        queryParams.putIfNotEmpty("cveTraitAssociation", commandOptions.cveTraitAssociation);
        queryParams.putIfNotEmpty("cveFunctionalEffect", commandOptions.cveFunctionalEffect);
        queryParams.putIfNotEmpty("cveTumorigenesis", commandOptions.cveTumorigenesis);
        queryParams.putIfNotEmpty("cveOtherClassification", commandOptions.cveOtherClassification);
        queryParams.putIfNotEmpty("cveRoleInCancer", commandOptions.cveRoleInCancer);
        queryParams.putIfNotEmpty("cveReviewAcmg", commandOptions.cveReviewAcmg);
        queryParams.putIfNotEmpty("cveReviewTier", commandOptions.cveReviewTier);
        queryParams.putIfNotEmpty("cveReviewClinicalSignificance", commandOptions.cveReviewClinicalSignificance);
        queryParams.putIfNotEmpty("cveReviewText", commandOptions.cveReviewText);
        queryParams.putIfNotEmpty("field", commandOptions.field);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return enterpriseOpenCGAClient.getEnterpriseCvdbAnalysisClient().aggregateCase(queryParams);
    }

    private RestResponse<ClinicalAnalysis> queryCase() throws Exception {
        logger.debug("Executing queryCase in CVDB command line");

        CVDBCommandOptions.QueryCaseCommandOptions commandOptions = cVDBCommandOptions.queryCaseCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("project", commandOptions.project);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("include", commandOptions.include);
        queryParams.putIfNotEmpty("exclude", commandOptions.exclude);
        queryParams.putIfNotNull("limit", commandOptions.limit);
        queryParams.putIfNotNull("skip", commandOptions.skip);
        queryParams.putIfNotEmpty("caId", commandOptions.caId);
        queryParams.putIfNotEmpty("caDescription", commandOptions.caDescription);
        queryParams.putIfNotEmpty("caType", commandOptions.caType);
        queryParams.putIfNotEmpty("caDisorderId", commandOptions.caDisorderId);
        queryParams.putIfNotEmpty("caFilename", commandOptions.caFilename);
        queryParams.putIfNotEmpty("caProbandId", commandOptions.caProbandId);
        queryParams.putIfNotEmpty("caProbandDisorderId", commandOptions.caProbandDisorderId);
        queryParams.putIfNotEmpty("caProbandPhenotypeName", commandOptions.caProbandPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyId", commandOptions.caFamilyId);
        queryParams.putIfNotEmpty("caFamilyPhenotypeName", commandOptions.caFamilyPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyMemberId", commandOptions.caFamilyMemberId);
        queryParams.putIfNotEmpty("caReport", commandOptions.caReport);
        queryParams.putIfNotEmpty("caStatus", commandOptions.caStatus);
        queryParams.putIfNotNull("caLocked", commandOptions.caLocked);
        queryParams.putIfNotEmpty("ciId", commandOptions.ciId);
        queryParams.putIfNotNull("ciPrimary", commandOptions.ciPrimary);
        queryParams.putIfNotEmpty("ciDescription", commandOptions.ciDescription);
        queryParams.putIfNotEmpty("ciPanelId", commandOptions.ciPanelId);
        queryParams.putIfNotEmpty("ciAnalystId", commandOptions.ciAnalystId);
        queryParams.putIfNotEmpty("ciAnalystName", commandOptions.ciAnalystName);
        queryParams.putIfNotEmpty("ciAnalystEmail", commandOptions.ciAnalystEmail);
        queryParams.putIfNotEmpty("ciAnalystAssignedBy", commandOptions.ciAnalystAssignedBy);
        queryParams.putIfNotEmpty("ciAnalystDate", commandOptions.ciAnalystDate);
        queryParams.putIfNotEmpty("ciMethodName", commandOptions.ciMethodName);
        queryParams.putIfNotEmpty("ciMethodVersion", commandOptions.ciMethodVersion);
        queryParams.putIfNotEmpty("ciMethodCommit", commandOptions.ciMethodCommit);
        queryParams.putIfNotEmpty("ciMethodDependencies", commandOptions.ciMethodDependencies);
        queryParams.putIfNotEmpty("ciComments", commandOptions.ciComments);
        queryParams.putIfNotNull("ciLocked", commandOptions.ciLocked);
        queryParams.putIfNotEmpty("ciStatusId", commandOptions.ciStatusId);
        queryParams.putIfNotEmpty("ciStatusName", commandOptions.ciStatusName);
        queryParams.putIfNotEmpty("ciStatusDescription", commandOptions.ciStatusDescription);
        queryParams.putIfNotEmpty("ciStatusDate", commandOptions.ciStatusDate);
        queryParams.putIfNotEmpty("ciCreationDate", commandOptions.ciCreationDate);
        queryParams.putIfNotEmpty("ciModificationDate", commandOptions.ciModificationDate);
        queryParams.putIfNotNull("ciVersion", commandOptions.ciVersion);
        queryParams.putIfNotEmpty("cvId", commandOptions.cvId);
        queryParams.putIfNotEmpty("cvVariantId", commandOptions.cvVariantId);
        queryParams.putIfNotNull("cvPrimaryFinding", commandOptions.cvPrimaryFinding);
        queryParams.putIfNotNull("cvPrimaryInterpretation", commandOptions.cvPrimaryInterpretation);
        queryParams.putIfNotEmpty("cvComments", commandOptions.cvComments);
        queryParams.putIfNotEmpty("cvDiscussionAuthor", commandOptions.cvDiscussionAuthor);
        queryParams.putIfNotEmpty("cvDiscussionDate", commandOptions.cvDiscussionDate);
        queryParams.putIfNotEmpty("cvDiscussionText", commandOptions.cvDiscussionText);
        queryParams.putIfNotEmpty("cvConfidenceValue", commandOptions.cvConfidenceValue);
        queryParams.putIfNotEmpty("cvConfidenceAuthor", commandOptions.cvConfidenceAuthor);
        queryParams.putIfNotEmpty("cvConfidenceDate", commandOptions.cvConfidenceDate);
        queryParams.putIfNotEmpty("cvTag", commandOptions.cvTag);
        queryParams.putIfNotEmpty("cvStatus", commandOptions.cvStatus);
        queryParams.putIfNotEmpty("cvRegion", commandOptions.cvRegion);
        queryParams.putIfNotEmpty("cvBiotype", commandOptions.cvBiotype);
        queryParams.putIfNotEmpty("cvCt", commandOptions.cvCt);
        queryParams.putIfNotEmpty("cvTranscriptFlag", commandOptions.cvTranscriptFlag);
        queryParams.putIfNotEmpty("cvGene", commandOptions.cvGene);
        queryParams.putIfNotEmpty("cvXref", commandOptions.cvXref);
        queryParams.putIfNotEmpty("cvAnnotRoleInCancerGenes", commandOptions.cvAnnotRoleInCancerGenes);
        queryParams.putIfNotEmpty("cvType", commandOptions.cvType);
        queryParams.putIfNotEmpty("cvProteinSubstitution", commandOptions.cvProteinSubstitution);
        queryParams.putIfNotEmpty("cvConservation", commandOptions.cvConservation);
        queryParams.putIfNotEmpty("cvFunctionalScore", commandOptions.cvFunctionalScore);
        queryParams.putIfNotEmpty("cvPopulationFrequencyAlt", commandOptions.cvPopulationFrequencyAlt);
        queryParams.putIfNotEmpty("cvPopulationFrequencyMaf", commandOptions.cvPopulationFrequencyMaf);
        queryParams.putIfNotEmpty("cvPopulationFrequencyRef", commandOptions.cvPopulationFrequencyRef);
        queryParams.putIfNotEmpty("cvCohortStatsAlt", commandOptions.cvCohortStatsAlt);
        queryParams.putIfNotEmpty("cvCohortStatsMaf", commandOptions.cvCohortStatsMaf);
        queryParams.putIfNotEmpty("cvCohortStatsRef", commandOptions.cvCohortStatsRef);
        queryParams.putIfNotEmpty("cvCohortStatsPass", commandOptions.cvCohortStatsPass);
        queryParams.putIfNotEmpty("cvScore", commandOptions.cvScore);
        queryParams.putIfNotEmpty("cvAnnotGoGenes", commandOptions.cvAnnotGoGenes);
        queryParams.putIfNotEmpty("cvAnnotExpressionGenes", commandOptions.cvAnnotExpressionGenes);
        queryParams.putIfNotEmpty("cvGeneTraitId", commandOptions.cvGeneTraitId);
        queryParams.putIfNotEmpty("cvTrait", commandOptions.cvTrait);
        queryParams.putIfNotEmpty("cvProteinKeyword", commandOptions.cvProteinKeyword);
        queryParams.putIfNotEmpty("cveVariantId", commandOptions.cveVariantId);
        queryParams.putIfNotNull("cvePrimaryFinding", commandOptions.cvePrimaryFinding);
        queryParams.putIfNotNull("cvePrimaryInterpretation", commandOptions.cvePrimaryInterpretation);
        queryParams.putIfNotEmpty("cvePhenotypeName", commandOptions.cvePhenotypeName);
        queryParams.putIfNotEmpty("cveGeneName", commandOptions.cveGeneName);
        queryParams.putIfNotEmpty("cveTranscriptId", commandOptions.cveTranscriptId);
        queryParams.putIfNotEmpty("cveSoTermName", commandOptions.cveSoTermName);
        queryParams.putIfNotEmpty("cveXrefId", commandOptions.cveXrefId);
        queryParams.putIfNotEmpty("cvePanelId", commandOptions.cvePanelId);
        queryParams.putIfNotEmpty("cveMoi", commandOptions.cveMoi);
        queryParams.putIfNotEmpty("cvePenetrance", commandOptions.cvePenetrance);
        queryParams.putIfNotEmpty("cveAcmg", commandOptions.cveAcmg);
        queryParams.putIfNotEmpty("cveTier", commandOptions.cveTier);
        queryParams.putIfNotEmpty("cveClinicalSignificance", commandOptions.cveClinicalSignificance);
        queryParams.putIfNotEmpty("cveDrugResponse", commandOptions.cveDrugResponse);
        queryParams.putIfNotEmpty("cveTraitAssociation", commandOptions.cveTraitAssociation);
        queryParams.putIfNotEmpty("cveFunctionalEffect", commandOptions.cveFunctionalEffect);
        queryParams.putIfNotEmpty("cveTumorigenesis", commandOptions.cveTumorigenesis);
        queryParams.putIfNotEmpty("cveOtherClassification", commandOptions.cveOtherClassification);
        queryParams.putIfNotEmpty("cveRoleInCancer", commandOptions.cveRoleInCancer);
        queryParams.putIfNotEmpty("cveReviewAcmg", commandOptions.cveReviewAcmg);
        queryParams.putIfNotEmpty("cveReviewTier", commandOptions.cveReviewTier);
        queryParams.putIfNotEmpty("cveReviewClinicalSignificance", commandOptions.cveReviewClinicalSignificance);
        queryParams.putIfNotEmpty("cveReviewText", commandOptions.cveReviewText);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return enterpriseOpenCGAClient.getEnterpriseCvdbAnalysisClient().queryCase(queryParams);
    }

    private RestResponse<FacetField> aggregateClinicalVariant() throws Exception {
        logger.debug("Executing aggregateClinicalVariant in CVDB command line");

        CVDBCommandOptions.AggregateClinicalVariantCommandOptions commandOptions = cVDBCommandOptions.aggregateClinicalVariantCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("project", commandOptions.project);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("caId", commandOptions.caId);
        queryParams.putIfNotEmpty("caDescription", commandOptions.caDescription);
        queryParams.putIfNotEmpty("caType", commandOptions.caType);
        queryParams.putIfNotEmpty("caDisorderId", commandOptions.caDisorderId);
        queryParams.putIfNotEmpty("caFilename", commandOptions.caFilename);
        queryParams.putIfNotEmpty("caProbandId", commandOptions.caProbandId);
        queryParams.putIfNotEmpty("caProbandDisorderId", commandOptions.caProbandDisorderId);
        queryParams.putIfNotEmpty("caProbandPhenotypeName", commandOptions.caProbandPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyId", commandOptions.caFamilyId);
        queryParams.putIfNotEmpty("caFamilyPhenotypeName", commandOptions.caFamilyPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyMemberId", commandOptions.caFamilyMemberId);
        queryParams.putIfNotEmpty("caReport", commandOptions.caReport);
        queryParams.putIfNotEmpty("caStatus", commandOptions.caStatus);
        queryParams.putIfNotNull("caLocked", commandOptions.caLocked);
        queryParams.putIfNotEmpty("ciId", commandOptions.ciId);
        queryParams.putIfNotNull("ciPrimary", commandOptions.ciPrimary);
        queryParams.putIfNotEmpty("ciDescription", commandOptions.ciDescription);
        queryParams.putIfNotEmpty("ciPanelId", commandOptions.ciPanelId);
        queryParams.putIfNotEmpty("ciAnalystId", commandOptions.ciAnalystId);
        queryParams.putIfNotEmpty("ciAnalystName", commandOptions.ciAnalystName);
        queryParams.putIfNotEmpty("ciAnalystEmail", commandOptions.ciAnalystEmail);
        queryParams.putIfNotEmpty("ciAnalystAssignedBy", commandOptions.ciAnalystAssignedBy);
        queryParams.putIfNotEmpty("ciAnalystDate", commandOptions.ciAnalystDate);
        queryParams.putIfNotEmpty("ciMethodName", commandOptions.ciMethodName);
        queryParams.putIfNotEmpty("ciMethodVersion", commandOptions.ciMethodVersion);
        queryParams.putIfNotEmpty("ciMethodCommit", commandOptions.ciMethodCommit);
        queryParams.putIfNotEmpty("ciMethodDependencies", commandOptions.ciMethodDependencies);
        queryParams.putIfNotEmpty("ciComments", commandOptions.ciComments);
        queryParams.putIfNotNull("ciLocked", commandOptions.ciLocked);
        queryParams.putIfNotEmpty("ciStatusId", commandOptions.ciStatusId);
        queryParams.putIfNotEmpty("ciStatusName", commandOptions.ciStatusName);
        queryParams.putIfNotEmpty("ciStatusDescription", commandOptions.ciStatusDescription);
        queryParams.putIfNotEmpty("ciStatusDate", commandOptions.ciStatusDate);
        queryParams.putIfNotEmpty("ciCreationDate", commandOptions.ciCreationDate);
        queryParams.putIfNotEmpty("ciModificationDate", commandOptions.ciModificationDate);
        queryParams.putIfNotNull("ciVersion", commandOptions.ciVersion);
        queryParams.putIfNotEmpty("cvId", commandOptions.cvId);
        queryParams.putIfNotEmpty("cvVariantId", commandOptions.cvVariantId);
        queryParams.putIfNotNull("cvPrimaryFinding", commandOptions.cvPrimaryFinding);
        queryParams.putIfNotNull("cvPrimaryInterpretation", commandOptions.cvPrimaryInterpretation);
        queryParams.putIfNotEmpty("cvComments", commandOptions.cvComments);
        queryParams.putIfNotEmpty("cvDiscussionAuthor", commandOptions.cvDiscussionAuthor);
        queryParams.putIfNotEmpty("cvDiscussionDate", commandOptions.cvDiscussionDate);
        queryParams.putIfNotEmpty("cvDiscussionText", commandOptions.cvDiscussionText);
        queryParams.putIfNotEmpty("cvConfidenceValue", commandOptions.cvConfidenceValue);
        queryParams.putIfNotEmpty("cvConfidenceAuthor", commandOptions.cvConfidenceAuthor);
        queryParams.putIfNotEmpty("cvConfidenceDate", commandOptions.cvConfidenceDate);
        queryParams.putIfNotEmpty("cvTag", commandOptions.cvTag);
        queryParams.putIfNotEmpty("cvStatus", commandOptions.cvStatus);
        queryParams.putIfNotEmpty("cvRegion", commandOptions.cvRegion);
        queryParams.putIfNotEmpty("cvBiotype", commandOptions.cvBiotype);
        queryParams.putIfNotEmpty("cvCt", commandOptions.cvCt);
        queryParams.putIfNotEmpty("cvTranscriptFlag", commandOptions.cvTranscriptFlag);
        queryParams.putIfNotEmpty("cvGene", commandOptions.cvGene);
        queryParams.putIfNotEmpty("cvXref", commandOptions.cvXref);
        queryParams.putIfNotEmpty("cvAnnotRoleInCancerGenes", commandOptions.cvAnnotRoleInCancerGenes);
        queryParams.putIfNotEmpty("cvType", commandOptions.cvType);
        queryParams.putIfNotEmpty("cvProteinSubstitution", commandOptions.cvProteinSubstitution);
        queryParams.putIfNotEmpty("cvConservation", commandOptions.cvConservation);
        queryParams.putIfNotEmpty("cvFunctionalScore", commandOptions.cvFunctionalScore);
        queryParams.putIfNotEmpty("cvPopulationFrequencyAlt", commandOptions.cvPopulationFrequencyAlt);
        queryParams.putIfNotEmpty("cvPopulationFrequencyMaf", commandOptions.cvPopulationFrequencyMaf);
        queryParams.putIfNotEmpty("cvPopulationFrequencyRef", commandOptions.cvPopulationFrequencyRef);
        queryParams.putIfNotEmpty("cvCohortStatsAlt", commandOptions.cvCohortStatsAlt);
        queryParams.putIfNotEmpty("cvCohortStatsMaf", commandOptions.cvCohortStatsMaf);
        queryParams.putIfNotEmpty("cvCohortStatsRef", commandOptions.cvCohortStatsRef);
        queryParams.putIfNotEmpty("cvCohortStatsPass", commandOptions.cvCohortStatsPass);
        queryParams.putIfNotEmpty("cvScore", commandOptions.cvScore);
        queryParams.putIfNotEmpty("cvAnnotGoGenes", commandOptions.cvAnnotGoGenes);
        queryParams.putIfNotEmpty("cvAnnotExpressionGenes", commandOptions.cvAnnotExpressionGenes);
        queryParams.putIfNotEmpty("cvGeneTraitId", commandOptions.cvGeneTraitId);
        queryParams.putIfNotEmpty("cvTrait", commandOptions.cvTrait);
        queryParams.putIfNotEmpty("cvProteinKeyword", commandOptions.cvProteinKeyword);
        queryParams.putIfNotEmpty("cveVariantId", commandOptions.cveVariantId);
        queryParams.putIfNotNull("cvePrimaryFinding", commandOptions.cvePrimaryFinding);
        queryParams.putIfNotNull("cvePrimaryInterpretation", commandOptions.cvePrimaryInterpretation);
        queryParams.putIfNotEmpty("cvePhenotypeName", commandOptions.cvePhenotypeName);
        queryParams.putIfNotEmpty("cveGeneName", commandOptions.cveGeneName);
        queryParams.putIfNotEmpty("cveTranscriptId", commandOptions.cveTranscriptId);
        queryParams.putIfNotEmpty("cveSoTermName", commandOptions.cveSoTermName);
        queryParams.putIfNotEmpty("cveXrefId", commandOptions.cveXrefId);
        queryParams.putIfNotEmpty("cvePanelId", commandOptions.cvePanelId);
        queryParams.putIfNotEmpty("cveMoi", commandOptions.cveMoi);
        queryParams.putIfNotEmpty("cvePenetrance", commandOptions.cvePenetrance);
        queryParams.putIfNotEmpty("cveAcmg", commandOptions.cveAcmg);
        queryParams.putIfNotEmpty("cveTier", commandOptions.cveTier);
        queryParams.putIfNotEmpty("cveClinicalSignificance", commandOptions.cveClinicalSignificance);
        queryParams.putIfNotEmpty("cveDrugResponse", commandOptions.cveDrugResponse);
        queryParams.putIfNotEmpty("cveTraitAssociation", commandOptions.cveTraitAssociation);
        queryParams.putIfNotEmpty("cveFunctionalEffect", commandOptions.cveFunctionalEffect);
        queryParams.putIfNotEmpty("cveTumorigenesis", commandOptions.cveTumorigenesis);
        queryParams.putIfNotEmpty("cveOtherClassification", commandOptions.cveOtherClassification);
        queryParams.putIfNotEmpty("cveRoleInCancer", commandOptions.cveRoleInCancer);
        queryParams.putIfNotEmpty("cveReviewAcmg", commandOptions.cveReviewAcmg);
        queryParams.putIfNotEmpty("cveReviewTier", commandOptions.cveReviewTier);
        queryParams.putIfNotEmpty("cveReviewClinicalSignificance", commandOptions.cveReviewClinicalSignificance);
        queryParams.putIfNotEmpty("cveReviewText", commandOptions.cveReviewText);
        queryParams.putIfNotEmpty("field", commandOptions.field);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return enterpriseOpenCGAClient.getEnterpriseCvdbAnalysisClient().aggregateClinicalVariant(queryParams);
    }

    private RestResponse<ClinicalVariant> queryClinicalVariant() throws Exception {
        logger.debug("Executing queryClinicalVariant in CVDB command line");

        CVDBCommandOptions.QueryClinicalVariantCommandOptions commandOptions = cVDBCommandOptions.queryClinicalVariantCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("project", commandOptions.project);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("include", commandOptions.include);
        queryParams.putIfNotEmpty("exclude", commandOptions.exclude);
        queryParams.putIfNotNull("limit", commandOptions.limit);
        queryParams.putIfNotNull("skip", commandOptions.skip);
        queryParams.putIfNotEmpty("caId", commandOptions.caId);
        queryParams.putIfNotEmpty("caDescription", commandOptions.caDescription);
        queryParams.putIfNotEmpty("caType", commandOptions.caType);
        queryParams.putIfNotEmpty("caDisorderId", commandOptions.caDisorderId);
        queryParams.putIfNotEmpty("caFilename", commandOptions.caFilename);
        queryParams.putIfNotEmpty("caProbandId", commandOptions.caProbandId);
        queryParams.putIfNotEmpty("caProbandDisorderId", commandOptions.caProbandDisorderId);
        queryParams.putIfNotEmpty("caProbandPhenotypeName", commandOptions.caProbandPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyId", commandOptions.caFamilyId);
        queryParams.putIfNotEmpty("caFamilyPhenotypeName", commandOptions.caFamilyPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyMemberId", commandOptions.caFamilyMemberId);
        queryParams.putIfNotEmpty("caReport", commandOptions.caReport);
        queryParams.putIfNotEmpty("caStatus", commandOptions.caStatus);
        queryParams.putIfNotNull("caLocked", commandOptions.caLocked);
        queryParams.putIfNotEmpty("ciId", commandOptions.ciId);
        queryParams.putIfNotNull("ciPrimary", commandOptions.ciPrimary);
        queryParams.putIfNotEmpty("ciDescription", commandOptions.ciDescription);
        queryParams.putIfNotEmpty("ciPanelId", commandOptions.ciPanelId);
        queryParams.putIfNotEmpty("ciAnalystId", commandOptions.ciAnalystId);
        queryParams.putIfNotEmpty("ciAnalystName", commandOptions.ciAnalystName);
        queryParams.putIfNotEmpty("ciAnalystEmail", commandOptions.ciAnalystEmail);
        queryParams.putIfNotEmpty("ciAnalystAssignedBy", commandOptions.ciAnalystAssignedBy);
        queryParams.putIfNotEmpty("ciAnalystDate", commandOptions.ciAnalystDate);
        queryParams.putIfNotEmpty("ciMethodName", commandOptions.ciMethodName);
        queryParams.putIfNotEmpty("ciMethodVersion", commandOptions.ciMethodVersion);
        queryParams.putIfNotEmpty("ciMethodCommit", commandOptions.ciMethodCommit);
        queryParams.putIfNotEmpty("ciMethodDependencies", commandOptions.ciMethodDependencies);
        queryParams.putIfNotEmpty("ciComments", commandOptions.ciComments);
        queryParams.putIfNotNull("ciLocked", commandOptions.ciLocked);
        queryParams.putIfNotEmpty("ciStatusId", commandOptions.ciStatusId);
        queryParams.putIfNotEmpty("ciStatusName", commandOptions.ciStatusName);
        queryParams.putIfNotEmpty("ciStatusDescription", commandOptions.ciStatusDescription);
        queryParams.putIfNotEmpty("ciStatusDate", commandOptions.ciStatusDate);
        queryParams.putIfNotEmpty("ciCreationDate", commandOptions.ciCreationDate);
        queryParams.putIfNotEmpty("ciModificationDate", commandOptions.ciModificationDate);
        queryParams.putIfNotNull("ciVersion", commandOptions.ciVersion);
        queryParams.putIfNotEmpty("cvId", commandOptions.cvId);
        queryParams.putIfNotEmpty("cvVariantId", commandOptions.cvVariantId);
        queryParams.putIfNotNull("cvPrimaryFinding", commandOptions.cvPrimaryFinding);
        queryParams.putIfNotNull("cvPrimaryInterpretation", commandOptions.cvPrimaryInterpretation);
        queryParams.putIfNotEmpty("cvComments", commandOptions.cvComments);
        queryParams.putIfNotEmpty("cvDiscussionAuthor", commandOptions.cvDiscussionAuthor);
        queryParams.putIfNotEmpty("cvDiscussionDate", commandOptions.cvDiscussionDate);
        queryParams.putIfNotEmpty("cvDiscussionText", commandOptions.cvDiscussionText);
        queryParams.putIfNotEmpty("cvConfidenceValue", commandOptions.cvConfidenceValue);
        queryParams.putIfNotEmpty("cvConfidenceAuthor", commandOptions.cvConfidenceAuthor);
        queryParams.putIfNotEmpty("cvConfidenceDate", commandOptions.cvConfidenceDate);
        queryParams.putIfNotEmpty("cvTag", commandOptions.cvTag);
        queryParams.putIfNotEmpty("cvStatus", commandOptions.cvStatus);
        queryParams.putIfNotEmpty("cvRegion", commandOptions.cvRegion);
        queryParams.putIfNotEmpty("cvBiotype", commandOptions.cvBiotype);
        queryParams.putIfNotEmpty("cvCt", commandOptions.cvCt);
        queryParams.putIfNotEmpty("cvTranscriptFlag", commandOptions.cvTranscriptFlag);
        queryParams.putIfNotEmpty("cvGene", commandOptions.cvGene);
        queryParams.putIfNotEmpty("cvXref", commandOptions.cvXref);
        queryParams.putIfNotEmpty("cvAnnotRoleInCancerGenes", commandOptions.cvAnnotRoleInCancerGenes);
        queryParams.putIfNotEmpty("cvType", commandOptions.cvType);
        queryParams.putIfNotEmpty("cvProteinSubstitution", commandOptions.cvProteinSubstitution);
        queryParams.putIfNotEmpty("cvConservation", commandOptions.cvConservation);
        queryParams.putIfNotEmpty("cvFunctionalScore", commandOptions.cvFunctionalScore);
        queryParams.putIfNotEmpty("cvPopulationFrequencyAlt", commandOptions.cvPopulationFrequencyAlt);
        queryParams.putIfNotEmpty("cvPopulationFrequencyMaf", commandOptions.cvPopulationFrequencyMaf);
        queryParams.putIfNotEmpty("cvPopulationFrequencyRef", commandOptions.cvPopulationFrequencyRef);
        queryParams.putIfNotEmpty("cvCohortStatsAlt", commandOptions.cvCohortStatsAlt);
        queryParams.putIfNotEmpty("cvCohortStatsMaf", commandOptions.cvCohortStatsMaf);
        queryParams.putIfNotEmpty("cvCohortStatsRef", commandOptions.cvCohortStatsRef);
        queryParams.putIfNotEmpty("cvCohortStatsPass", commandOptions.cvCohortStatsPass);
        queryParams.putIfNotEmpty("cvScore", commandOptions.cvScore);
        queryParams.putIfNotEmpty("cvAnnotGoGenes", commandOptions.cvAnnotGoGenes);
        queryParams.putIfNotEmpty("cvAnnotExpressionGenes", commandOptions.cvAnnotExpressionGenes);
        queryParams.putIfNotEmpty("cvGeneTraitId", commandOptions.cvGeneTraitId);
        queryParams.putIfNotEmpty("cvTrait", commandOptions.cvTrait);
        queryParams.putIfNotEmpty("cvProteinKeyword", commandOptions.cvProteinKeyword);
        queryParams.putIfNotEmpty("cveVariantId", commandOptions.cveVariantId);
        queryParams.putIfNotNull("cvePrimaryFinding", commandOptions.cvePrimaryFinding);
        queryParams.putIfNotNull("cvePrimaryInterpretation", commandOptions.cvePrimaryInterpretation);
        queryParams.putIfNotEmpty("cvePhenotypeName", commandOptions.cvePhenotypeName);
        queryParams.putIfNotEmpty("cveGeneName", commandOptions.cveGeneName);
        queryParams.putIfNotEmpty("cveTranscriptId", commandOptions.cveTranscriptId);
        queryParams.putIfNotEmpty("cveSoTermName", commandOptions.cveSoTermName);
        queryParams.putIfNotEmpty("cveXrefId", commandOptions.cveXrefId);
        queryParams.putIfNotEmpty("cvePanelId", commandOptions.cvePanelId);
        queryParams.putIfNotEmpty("cveMoi", commandOptions.cveMoi);
        queryParams.putIfNotEmpty("cvePenetrance", commandOptions.cvePenetrance);
        queryParams.putIfNotEmpty("cveAcmg", commandOptions.cveAcmg);
        queryParams.putIfNotEmpty("cveTier", commandOptions.cveTier);
        queryParams.putIfNotEmpty("cveClinicalSignificance", commandOptions.cveClinicalSignificance);
        queryParams.putIfNotEmpty("cveDrugResponse", commandOptions.cveDrugResponse);
        queryParams.putIfNotEmpty("cveTraitAssociation", commandOptions.cveTraitAssociation);
        queryParams.putIfNotEmpty("cveFunctionalEffect", commandOptions.cveFunctionalEffect);
        queryParams.putIfNotEmpty("cveTumorigenesis", commandOptions.cveTumorigenesis);
        queryParams.putIfNotEmpty("cveOtherClassification", commandOptions.cveOtherClassification);
        queryParams.putIfNotEmpty("cveRoleInCancer", commandOptions.cveRoleInCancer);
        queryParams.putIfNotEmpty("cveReviewAcmg", commandOptions.cveReviewAcmg);
        queryParams.putIfNotEmpty("cveReviewTier", commandOptions.cveReviewTier);
        queryParams.putIfNotEmpty("cveReviewClinicalSignificance", commandOptions.cveReviewClinicalSignificance);
        queryParams.putIfNotEmpty("cveReviewText", commandOptions.cveReviewText);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return enterpriseOpenCGAClient.getEnterpriseCvdbAnalysisClient().queryClinicalVariant(queryParams);
    }

    private RestResponse<ClinicalVariantSummaryStats> statsClinicalVariant() throws Exception {
        logger.debug("Executing statsClinicalVariant in CVDB command line");

        CVDBCommandOptions.StatsClinicalVariantCommandOptions commandOptions = cVDBCommandOptions.statsClinicalVariantCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("project", commandOptions.project);
        queryParams.putIfNotEmpty("ciStatusId", commandOptions.ciStatusId);
        queryParams.putIfNotEmpty("statsOrder", commandOptions.statsOrder);
        queryParams.putIfNotNull("statsLimit", commandOptions.statsLimit);

        return enterpriseOpenCGAClient.getEnterpriseCvdbAnalysisClient().statsClinicalVariant(commandOptions.variantIds, queryParams);
    }

    private RestResponse<Job> runIndex() throws Exception {
        logger.debug("Executing runIndex in CVDB command line");

        CVDBCommandOptions.RunIndexCommandOptions commandOptions = cVDBCommandOptions.runIndexCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("jobId", commandOptions.jobId);
        queryParams.putIfNotEmpty("jobDescription", commandOptions.jobDescription);
        queryParams.putIfNotEmpty("jobDependsOn", commandOptions.jobDependsOn);
        queryParams.putIfNotEmpty("jobTags", commandOptions.jobTags);
        queryParams.putIfNotEmpty("jobScheduledStartTime", commandOptions.jobScheduledStartTime);
        queryParams.putIfNotEmpty("jobPriority", commandOptions.jobPriority);
        queryParams.putIfNotNull("jobDryRun", commandOptions.jobDryRun);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }


        CvdbIndexTaskParams cvdbIndexTaskParams = null;
        if (commandOptions.jsonDataModel) {
            RestResponse<Job> res = new RestResponse<>();
            res.setType(QueryType.VOID);
            PrintUtils.println(getObjectAsJSON(categoryName,"/{apiVersion}/analysis/cvdb/index/run"));
            return res;
        } else if (commandOptions.jsonFile != null) {
            cvdbIndexTaskParams = JacksonUtils.getDefaultObjectMapper()
                    .readValue(new java.io.File(commandOptions.jsonFile), CvdbIndexTaskParams.class);
        } else {
            ObjectMap beanParams = new ObjectMap();
            putNestedIfNotNull(beanParams, "clinicalAnalysisIds", commandOptions.clinicalAnalysisIds, true);
            putNestedIfNotNull(beanParams, "allProject", commandOptions.allProject, true);
            putNestedIfNotNull(beanParams, "overwrite", commandOptions.overwrite, true);

            cvdbIndexTaskParams = JacksonUtils.getDefaultObjectMapper().copy()
                    .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, true)
                    .readValue(beanParams.toJson(), CvdbIndexTaskParams.class);
        }
        return enterpriseOpenCGAClient.getEnterpriseCvdbAnalysisClient().runIndex(cvdbIndexTaskParams, queryParams);
    }

    private RestResponse<FacetField> aggregateInterpretation() throws Exception {
        logger.debug("Executing aggregateInterpretation in CVDB command line");

        CVDBCommandOptions.AggregateInterpretationCommandOptions commandOptions = cVDBCommandOptions.aggregateInterpretationCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("project", commandOptions.project);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("caId", commandOptions.caId);
        queryParams.putIfNotEmpty("caDescription", commandOptions.caDescription);
        queryParams.putIfNotEmpty("caType", commandOptions.caType);
        queryParams.putIfNotEmpty("caDisorderId", commandOptions.caDisorderId);
        queryParams.putIfNotEmpty("caFilename", commandOptions.caFilename);
        queryParams.putIfNotEmpty("caProbandId", commandOptions.caProbandId);
        queryParams.putIfNotEmpty("caProbandDisorderId", commandOptions.caProbandDisorderId);
        queryParams.putIfNotEmpty("caProbandPhenotypeName", commandOptions.caProbandPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyId", commandOptions.caFamilyId);
        queryParams.putIfNotEmpty("caFamilyPhenotypeName", commandOptions.caFamilyPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyMemberId", commandOptions.caFamilyMemberId);
        queryParams.putIfNotEmpty("caReport", commandOptions.caReport);
        queryParams.putIfNotEmpty("caStatus", commandOptions.caStatus);
        queryParams.putIfNotNull("caLocked", commandOptions.caLocked);
        queryParams.putIfNotEmpty("ciId", commandOptions.ciId);
        queryParams.putIfNotNull("ciPrimary", commandOptions.ciPrimary);
        queryParams.putIfNotEmpty("ciDescription", commandOptions.ciDescription);
        queryParams.putIfNotEmpty("ciPanelId", commandOptions.ciPanelId);
        queryParams.putIfNotEmpty("ciAnalystId", commandOptions.ciAnalystId);
        queryParams.putIfNotEmpty("ciAnalystName", commandOptions.ciAnalystName);
        queryParams.putIfNotEmpty("ciAnalystEmail", commandOptions.ciAnalystEmail);
        queryParams.putIfNotEmpty("ciAnalystAssignedBy", commandOptions.ciAnalystAssignedBy);
        queryParams.putIfNotEmpty("ciAnalystDate", commandOptions.ciAnalystDate);
        queryParams.putIfNotEmpty("ciMethodName", commandOptions.ciMethodName);
        queryParams.putIfNotEmpty("ciMethodVersion", commandOptions.ciMethodVersion);
        queryParams.putIfNotEmpty("ciMethodCommit", commandOptions.ciMethodCommit);
        queryParams.putIfNotEmpty("ciMethodDependencies", commandOptions.ciMethodDependencies);
        queryParams.putIfNotEmpty("ciComments", commandOptions.ciComments);
        queryParams.putIfNotNull("ciLocked", commandOptions.ciLocked);
        queryParams.putIfNotEmpty("ciStatusId", commandOptions.ciStatusId);
        queryParams.putIfNotEmpty("ciStatusName", commandOptions.ciStatusName);
        queryParams.putIfNotEmpty("ciStatusDescription", commandOptions.ciStatusDescription);
        queryParams.putIfNotEmpty("ciStatusDate", commandOptions.ciStatusDate);
        queryParams.putIfNotEmpty("ciCreationDate", commandOptions.ciCreationDate);
        queryParams.putIfNotEmpty("ciModificationDate", commandOptions.ciModificationDate);
        queryParams.putIfNotNull("ciVersion", commandOptions.ciVersion);
        queryParams.putIfNotEmpty("cvId", commandOptions.cvId);
        queryParams.putIfNotEmpty("cvVariantId", commandOptions.cvVariantId);
        queryParams.putIfNotNull("cvPrimaryFinding", commandOptions.cvPrimaryFinding);
        queryParams.putIfNotNull("cvPrimaryInterpretation", commandOptions.cvPrimaryInterpretation);
        queryParams.putIfNotEmpty("cvComments", commandOptions.cvComments);
        queryParams.putIfNotEmpty("cvDiscussionAuthor", commandOptions.cvDiscussionAuthor);
        queryParams.putIfNotEmpty("cvDiscussionDate", commandOptions.cvDiscussionDate);
        queryParams.putIfNotEmpty("cvDiscussionText", commandOptions.cvDiscussionText);
        queryParams.putIfNotEmpty("cvConfidenceValue", commandOptions.cvConfidenceValue);
        queryParams.putIfNotEmpty("cvConfidenceAuthor", commandOptions.cvConfidenceAuthor);
        queryParams.putIfNotEmpty("cvConfidenceDate", commandOptions.cvConfidenceDate);
        queryParams.putIfNotEmpty("cvTag", commandOptions.cvTag);
        queryParams.putIfNotEmpty("cvStatus", commandOptions.cvStatus);
        queryParams.putIfNotEmpty("cvRegion", commandOptions.cvRegion);
        queryParams.putIfNotEmpty("cvBiotype", commandOptions.cvBiotype);
        queryParams.putIfNotEmpty("cvCt", commandOptions.cvCt);
        queryParams.putIfNotEmpty("cvTranscriptFlag", commandOptions.cvTranscriptFlag);
        queryParams.putIfNotEmpty("cvGene", commandOptions.cvGene);
        queryParams.putIfNotEmpty("cvXref", commandOptions.cvXref);
        queryParams.putIfNotEmpty("cvAnnotRoleInCancerGenes", commandOptions.cvAnnotRoleInCancerGenes);
        queryParams.putIfNotEmpty("cvType", commandOptions.cvType);
        queryParams.putIfNotEmpty("cvProteinSubstitution", commandOptions.cvProteinSubstitution);
        queryParams.putIfNotEmpty("cvConservation", commandOptions.cvConservation);
        queryParams.putIfNotEmpty("cvFunctionalScore", commandOptions.cvFunctionalScore);
        queryParams.putIfNotEmpty("cvPopulationFrequencyAlt", commandOptions.cvPopulationFrequencyAlt);
        queryParams.putIfNotEmpty("cvPopulationFrequencyMaf", commandOptions.cvPopulationFrequencyMaf);
        queryParams.putIfNotEmpty("cvPopulationFrequencyRef", commandOptions.cvPopulationFrequencyRef);
        queryParams.putIfNotEmpty("cvCohortStatsAlt", commandOptions.cvCohortStatsAlt);
        queryParams.putIfNotEmpty("cvCohortStatsMaf", commandOptions.cvCohortStatsMaf);
        queryParams.putIfNotEmpty("cvCohortStatsRef", commandOptions.cvCohortStatsRef);
        queryParams.putIfNotEmpty("cvCohortStatsPass", commandOptions.cvCohortStatsPass);
        queryParams.putIfNotEmpty("cvScore", commandOptions.cvScore);
        queryParams.putIfNotEmpty("cvAnnotGoGenes", commandOptions.cvAnnotGoGenes);
        queryParams.putIfNotEmpty("cvAnnotExpressionGenes", commandOptions.cvAnnotExpressionGenes);
        queryParams.putIfNotEmpty("cvGeneTraitId", commandOptions.cvGeneTraitId);
        queryParams.putIfNotEmpty("cvTrait", commandOptions.cvTrait);
        queryParams.putIfNotEmpty("cvProteinKeyword", commandOptions.cvProteinKeyword);
        queryParams.putIfNotEmpty("cveVariantId", commandOptions.cveVariantId);
        queryParams.putIfNotNull("cvePrimaryFinding", commandOptions.cvePrimaryFinding);
        queryParams.putIfNotNull("cvePrimaryInterpretation", commandOptions.cvePrimaryInterpretation);
        queryParams.putIfNotEmpty("cvePhenotypeName", commandOptions.cvePhenotypeName);
        queryParams.putIfNotEmpty("cveGeneName", commandOptions.cveGeneName);
        queryParams.putIfNotEmpty("cveTranscriptId", commandOptions.cveTranscriptId);
        queryParams.putIfNotEmpty("cveSoTermName", commandOptions.cveSoTermName);
        queryParams.putIfNotEmpty("cveXrefId", commandOptions.cveXrefId);
        queryParams.putIfNotEmpty("cvePanelId", commandOptions.cvePanelId);
        queryParams.putIfNotEmpty("cveMoi", commandOptions.cveMoi);
        queryParams.putIfNotEmpty("cvePenetrance", commandOptions.cvePenetrance);
        queryParams.putIfNotEmpty("cveAcmg", commandOptions.cveAcmg);
        queryParams.putIfNotEmpty("cveTier", commandOptions.cveTier);
        queryParams.putIfNotEmpty("cveClinicalSignificance", commandOptions.cveClinicalSignificance);
        queryParams.putIfNotEmpty("cveDrugResponse", commandOptions.cveDrugResponse);
        queryParams.putIfNotEmpty("cveTraitAssociation", commandOptions.cveTraitAssociation);
        queryParams.putIfNotEmpty("cveFunctionalEffect", commandOptions.cveFunctionalEffect);
        queryParams.putIfNotEmpty("cveTumorigenesis", commandOptions.cveTumorigenesis);
        queryParams.putIfNotEmpty("cveOtherClassification", commandOptions.cveOtherClassification);
        queryParams.putIfNotEmpty("cveRoleInCancer", commandOptions.cveRoleInCancer);
        queryParams.putIfNotEmpty("cveReviewAcmg", commandOptions.cveReviewAcmg);
        queryParams.putIfNotEmpty("cveReviewTier", commandOptions.cveReviewTier);
        queryParams.putIfNotEmpty("cveReviewClinicalSignificance", commandOptions.cveReviewClinicalSignificance);
        queryParams.putIfNotEmpty("cveReviewText", commandOptions.cveReviewText);
        queryParams.putIfNotEmpty("field", commandOptions.field);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return enterpriseOpenCGAClient.getEnterpriseCvdbAnalysisClient().aggregateInterpretation(queryParams);
    }

    private RestResponse<Interpretation> queryInterpretation() throws Exception {
        logger.debug("Executing queryInterpretation in CVDB command line");

        CVDBCommandOptions.QueryInterpretationCommandOptions commandOptions = cVDBCommandOptions.queryInterpretationCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("project", commandOptions.project);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("include", commandOptions.include);
        queryParams.putIfNotEmpty("exclude", commandOptions.exclude);
        queryParams.putIfNotNull("limit", commandOptions.limit);
        queryParams.putIfNotNull("skip", commandOptions.skip);
        queryParams.putIfNotEmpty("caId", commandOptions.caId);
        queryParams.putIfNotEmpty("caDescription", commandOptions.caDescription);
        queryParams.putIfNotEmpty("caType", commandOptions.caType);
        queryParams.putIfNotEmpty("caDisorderId", commandOptions.caDisorderId);
        queryParams.putIfNotEmpty("caFilename", commandOptions.caFilename);
        queryParams.putIfNotEmpty("caProbandId", commandOptions.caProbandId);
        queryParams.putIfNotEmpty("caProbandDisorderId", commandOptions.caProbandDisorderId);
        queryParams.putIfNotEmpty("caProbandPhenotypeName", commandOptions.caProbandPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyId", commandOptions.caFamilyId);
        queryParams.putIfNotEmpty("caFamilyPhenotypeName", commandOptions.caFamilyPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyMemberId", commandOptions.caFamilyMemberId);
        queryParams.putIfNotEmpty("caReport", commandOptions.caReport);
        queryParams.putIfNotEmpty("caStatus", commandOptions.caStatus);
        queryParams.putIfNotNull("caLocked", commandOptions.caLocked);
        queryParams.putIfNotEmpty("ciId", commandOptions.ciId);
        queryParams.putIfNotNull("ciPrimary", commandOptions.ciPrimary);
        queryParams.putIfNotEmpty("ciDescription", commandOptions.ciDescription);
        queryParams.putIfNotEmpty("ciPanelId", commandOptions.ciPanelId);
        queryParams.putIfNotEmpty("ciAnalystId", commandOptions.ciAnalystId);
        queryParams.putIfNotEmpty("ciAnalystName", commandOptions.ciAnalystName);
        queryParams.putIfNotEmpty("ciAnalystEmail", commandOptions.ciAnalystEmail);
        queryParams.putIfNotEmpty("ciAnalystAssignedBy", commandOptions.ciAnalystAssignedBy);
        queryParams.putIfNotEmpty("ciAnalystDate", commandOptions.ciAnalystDate);
        queryParams.putIfNotEmpty("ciMethodName", commandOptions.ciMethodName);
        queryParams.putIfNotEmpty("ciMethodVersion", commandOptions.ciMethodVersion);
        queryParams.putIfNotEmpty("ciMethodCommit", commandOptions.ciMethodCommit);
        queryParams.putIfNotEmpty("ciMethodDependencies", commandOptions.ciMethodDependencies);
        queryParams.putIfNotEmpty("ciComments", commandOptions.ciComments);
        queryParams.putIfNotNull("ciLocked", commandOptions.ciLocked);
        queryParams.putIfNotEmpty("ciStatusId", commandOptions.ciStatusId);
        queryParams.putIfNotEmpty("ciStatusName", commandOptions.ciStatusName);
        queryParams.putIfNotEmpty("ciStatusDescription", commandOptions.ciStatusDescription);
        queryParams.putIfNotEmpty("ciStatusDate", commandOptions.ciStatusDate);
        queryParams.putIfNotEmpty("ciCreationDate", commandOptions.ciCreationDate);
        queryParams.putIfNotEmpty("ciModificationDate", commandOptions.ciModificationDate);
        queryParams.putIfNotNull("ciVersion", commandOptions.ciVersion);
        queryParams.putIfNotEmpty("cvId", commandOptions.cvId);
        queryParams.putIfNotEmpty("cvVariantId", commandOptions.cvVariantId);
        queryParams.putIfNotNull("cvPrimaryFinding", commandOptions.cvPrimaryFinding);
        queryParams.putIfNotNull("cvPrimaryInterpretation", commandOptions.cvPrimaryInterpretation);
        queryParams.putIfNotEmpty("cvComments", commandOptions.cvComments);
        queryParams.putIfNotEmpty("cvDiscussionAuthor", commandOptions.cvDiscussionAuthor);
        queryParams.putIfNotEmpty("cvDiscussionDate", commandOptions.cvDiscussionDate);
        queryParams.putIfNotEmpty("cvDiscussionText", commandOptions.cvDiscussionText);
        queryParams.putIfNotEmpty("cvConfidenceValue", commandOptions.cvConfidenceValue);
        queryParams.putIfNotEmpty("cvConfidenceAuthor", commandOptions.cvConfidenceAuthor);
        queryParams.putIfNotEmpty("cvConfidenceDate", commandOptions.cvConfidenceDate);
        queryParams.putIfNotEmpty("cvTag", commandOptions.cvTag);
        queryParams.putIfNotEmpty("cvStatus", commandOptions.cvStatus);
        queryParams.putIfNotEmpty("cvRegion", commandOptions.cvRegion);
        queryParams.putIfNotEmpty("cvBiotype", commandOptions.cvBiotype);
        queryParams.putIfNotEmpty("cvCt", commandOptions.cvCt);
        queryParams.putIfNotEmpty("cvTranscriptFlag", commandOptions.cvTranscriptFlag);
        queryParams.putIfNotEmpty("cvGene", commandOptions.cvGene);
        queryParams.putIfNotEmpty("cvXref", commandOptions.cvXref);
        queryParams.putIfNotEmpty("cvAnnotRoleInCancerGenes", commandOptions.cvAnnotRoleInCancerGenes);
        queryParams.putIfNotEmpty("cvType", commandOptions.cvType);
        queryParams.putIfNotEmpty("cvProteinSubstitution", commandOptions.cvProteinSubstitution);
        queryParams.putIfNotEmpty("cvConservation", commandOptions.cvConservation);
        queryParams.putIfNotEmpty("cvFunctionalScore", commandOptions.cvFunctionalScore);
        queryParams.putIfNotEmpty("cvPopulationFrequencyAlt", commandOptions.cvPopulationFrequencyAlt);
        queryParams.putIfNotEmpty("cvPopulationFrequencyMaf", commandOptions.cvPopulationFrequencyMaf);
        queryParams.putIfNotEmpty("cvPopulationFrequencyRef", commandOptions.cvPopulationFrequencyRef);
        queryParams.putIfNotEmpty("cvCohortStatsAlt", commandOptions.cvCohortStatsAlt);
        queryParams.putIfNotEmpty("cvCohortStatsMaf", commandOptions.cvCohortStatsMaf);
        queryParams.putIfNotEmpty("cvCohortStatsRef", commandOptions.cvCohortStatsRef);
        queryParams.putIfNotEmpty("cvCohortStatsPass", commandOptions.cvCohortStatsPass);
        queryParams.putIfNotEmpty("cvScore", commandOptions.cvScore);
        queryParams.putIfNotEmpty("cvAnnotGoGenes", commandOptions.cvAnnotGoGenes);
        queryParams.putIfNotEmpty("cvAnnotExpressionGenes", commandOptions.cvAnnotExpressionGenes);
        queryParams.putIfNotEmpty("cvGeneTraitId", commandOptions.cvGeneTraitId);
        queryParams.putIfNotEmpty("cvTrait", commandOptions.cvTrait);
        queryParams.putIfNotEmpty("cvProteinKeyword", commandOptions.cvProteinKeyword);
        queryParams.putIfNotEmpty("cveVariantId", commandOptions.cveVariantId);
        queryParams.putIfNotNull("cvePrimaryFinding", commandOptions.cvePrimaryFinding);
        queryParams.putIfNotNull("cvePrimaryInterpretation", commandOptions.cvePrimaryInterpretation);
        queryParams.putIfNotEmpty("cvePhenotypeName", commandOptions.cvePhenotypeName);
        queryParams.putIfNotEmpty("cveGeneName", commandOptions.cveGeneName);
        queryParams.putIfNotEmpty("cveTranscriptId", commandOptions.cveTranscriptId);
        queryParams.putIfNotEmpty("cveSoTermName", commandOptions.cveSoTermName);
        queryParams.putIfNotEmpty("cveXrefId", commandOptions.cveXrefId);
        queryParams.putIfNotEmpty("cvePanelId", commandOptions.cvePanelId);
        queryParams.putIfNotEmpty("cveMoi", commandOptions.cveMoi);
        queryParams.putIfNotEmpty("cvePenetrance", commandOptions.cvePenetrance);
        queryParams.putIfNotEmpty("cveAcmg", commandOptions.cveAcmg);
        queryParams.putIfNotEmpty("cveTier", commandOptions.cveTier);
        queryParams.putIfNotEmpty("cveClinicalSignificance", commandOptions.cveClinicalSignificance);
        queryParams.putIfNotEmpty("cveDrugResponse", commandOptions.cveDrugResponse);
        queryParams.putIfNotEmpty("cveTraitAssociation", commandOptions.cveTraitAssociation);
        queryParams.putIfNotEmpty("cveFunctionalEffect", commandOptions.cveFunctionalEffect);
        queryParams.putIfNotEmpty("cveTumorigenesis", commandOptions.cveTumorigenesis);
        queryParams.putIfNotEmpty("cveOtherClassification", commandOptions.cveOtherClassification);
        queryParams.putIfNotEmpty("cveRoleInCancer", commandOptions.cveRoleInCancer);
        queryParams.putIfNotEmpty("cveReviewAcmg", commandOptions.cveReviewAcmg);
        queryParams.putIfNotEmpty("cveReviewTier", commandOptions.cveReviewTier);
        queryParams.putIfNotEmpty("cveReviewClinicalSignificance", commandOptions.cveReviewClinicalSignificance);
        queryParams.putIfNotEmpty("cveReviewText", commandOptions.cveReviewText);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return enterpriseOpenCGAClient.getEnterpriseCvdbAnalysisClient().queryInterpretation(queryParams);
    }

    private RestResponse<FacetField> aggregateVariantEvidence() throws Exception {
        logger.debug("Executing aggregateVariantEvidence in CVDB command line");

        CVDBCommandOptions.AggregateVariantEvidenceCommandOptions commandOptions = cVDBCommandOptions.aggregateVariantEvidenceCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("project", commandOptions.project);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("caId", commandOptions.caId);
        queryParams.putIfNotEmpty("caDescription", commandOptions.caDescription);
        queryParams.putIfNotEmpty("caType", commandOptions.caType);
        queryParams.putIfNotEmpty("caDisorderId", commandOptions.caDisorderId);
        queryParams.putIfNotEmpty("caFilename", commandOptions.caFilename);
        queryParams.putIfNotEmpty("caProbandId", commandOptions.caProbandId);
        queryParams.putIfNotEmpty("caProbandDisorderId", commandOptions.caProbandDisorderId);
        queryParams.putIfNotEmpty("caProbandPhenotypeName", commandOptions.caProbandPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyId", commandOptions.caFamilyId);
        queryParams.putIfNotEmpty("caFamilyPhenotypeName", commandOptions.caFamilyPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyMemberId", commandOptions.caFamilyMemberId);
        queryParams.putIfNotEmpty("caReport", commandOptions.caReport);
        queryParams.putIfNotEmpty("caStatus", commandOptions.caStatus);
        queryParams.putIfNotNull("caLocked", commandOptions.caLocked);
        queryParams.putIfNotEmpty("ciId", commandOptions.ciId);
        queryParams.putIfNotNull("ciPrimary", commandOptions.ciPrimary);
        queryParams.putIfNotEmpty("ciDescription", commandOptions.ciDescription);
        queryParams.putIfNotEmpty("ciPanelId", commandOptions.ciPanelId);
        queryParams.putIfNotEmpty("ciAnalystId", commandOptions.ciAnalystId);
        queryParams.putIfNotEmpty("ciAnalystName", commandOptions.ciAnalystName);
        queryParams.putIfNotEmpty("ciAnalystEmail", commandOptions.ciAnalystEmail);
        queryParams.putIfNotEmpty("ciAnalystAssignedBy", commandOptions.ciAnalystAssignedBy);
        queryParams.putIfNotEmpty("ciAnalystDate", commandOptions.ciAnalystDate);
        queryParams.putIfNotEmpty("ciMethodName", commandOptions.ciMethodName);
        queryParams.putIfNotEmpty("ciMethodVersion", commandOptions.ciMethodVersion);
        queryParams.putIfNotEmpty("ciMethodCommit", commandOptions.ciMethodCommit);
        queryParams.putIfNotEmpty("ciMethodDependencies", commandOptions.ciMethodDependencies);
        queryParams.putIfNotEmpty("ciComments", commandOptions.ciComments);
        queryParams.putIfNotNull("ciLocked", commandOptions.ciLocked);
        queryParams.putIfNotEmpty("ciStatusId", commandOptions.ciStatusId);
        queryParams.putIfNotEmpty("ciStatusName", commandOptions.ciStatusName);
        queryParams.putIfNotEmpty("ciStatusDescription", commandOptions.ciStatusDescription);
        queryParams.putIfNotEmpty("ciStatusDate", commandOptions.ciStatusDate);
        queryParams.putIfNotEmpty("ciCreationDate", commandOptions.ciCreationDate);
        queryParams.putIfNotEmpty("ciModificationDate", commandOptions.ciModificationDate);
        queryParams.putIfNotNull("ciVersion", commandOptions.ciVersion);
        queryParams.putIfNotEmpty("cvId", commandOptions.cvId);
        queryParams.putIfNotEmpty("cvVariantId", commandOptions.cvVariantId);
        queryParams.putIfNotNull("cvPrimaryFinding", commandOptions.cvPrimaryFinding);
        queryParams.putIfNotNull("cvPrimaryInterpretation", commandOptions.cvPrimaryInterpretation);
        queryParams.putIfNotEmpty("cvComments", commandOptions.cvComments);
        queryParams.putIfNotEmpty("cvDiscussionAuthor", commandOptions.cvDiscussionAuthor);
        queryParams.putIfNotEmpty("cvDiscussionDate", commandOptions.cvDiscussionDate);
        queryParams.putIfNotEmpty("cvDiscussionText", commandOptions.cvDiscussionText);
        queryParams.putIfNotEmpty("cvConfidenceValue", commandOptions.cvConfidenceValue);
        queryParams.putIfNotEmpty("cvConfidenceAuthor", commandOptions.cvConfidenceAuthor);
        queryParams.putIfNotEmpty("cvConfidenceDate", commandOptions.cvConfidenceDate);
        queryParams.putIfNotEmpty("cvTag", commandOptions.cvTag);
        queryParams.putIfNotEmpty("cvStatus", commandOptions.cvStatus);
        queryParams.putIfNotEmpty("cvRegion", commandOptions.cvRegion);
        queryParams.putIfNotEmpty("cvBiotype", commandOptions.cvBiotype);
        queryParams.putIfNotEmpty("cvCt", commandOptions.cvCt);
        queryParams.putIfNotEmpty("cvTranscriptFlag", commandOptions.cvTranscriptFlag);
        queryParams.putIfNotEmpty("cvGene", commandOptions.cvGene);
        queryParams.putIfNotEmpty("cvXref", commandOptions.cvXref);
        queryParams.putIfNotEmpty("cvAnnotRoleInCancerGenes", commandOptions.cvAnnotRoleInCancerGenes);
        queryParams.putIfNotEmpty("cvType", commandOptions.cvType);
        queryParams.putIfNotEmpty("cvProteinSubstitution", commandOptions.cvProteinSubstitution);
        queryParams.putIfNotEmpty("cvConservation", commandOptions.cvConservation);
        queryParams.putIfNotEmpty("cvFunctionalScore", commandOptions.cvFunctionalScore);
        queryParams.putIfNotEmpty("cvPopulationFrequencyAlt", commandOptions.cvPopulationFrequencyAlt);
        queryParams.putIfNotEmpty("cvPopulationFrequencyMaf", commandOptions.cvPopulationFrequencyMaf);
        queryParams.putIfNotEmpty("cvPopulationFrequencyRef", commandOptions.cvPopulationFrequencyRef);
        queryParams.putIfNotEmpty("cvCohortStatsAlt", commandOptions.cvCohortStatsAlt);
        queryParams.putIfNotEmpty("cvCohortStatsMaf", commandOptions.cvCohortStatsMaf);
        queryParams.putIfNotEmpty("cvCohortStatsRef", commandOptions.cvCohortStatsRef);
        queryParams.putIfNotEmpty("cvCohortStatsPass", commandOptions.cvCohortStatsPass);
        queryParams.putIfNotEmpty("cvScore", commandOptions.cvScore);
        queryParams.putIfNotEmpty("cvAnnotGoGenes", commandOptions.cvAnnotGoGenes);
        queryParams.putIfNotEmpty("cvAnnotExpressionGenes", commandOptions.cvAnnotExpressionGenes);
        queryParams.putIfNotEmpty("cvGeneTraitId", commandOptions.cvGeneTraitId);
        queryParams.putIfNotEmpty("cvTrait", commandOptions.cvTrait);
        queryParams.putIfNotEmpty("cvProteinKeyword", commandOptions.cvProteinKeyword);
        queryParams.putIfNotEmpty("cveVariantId", commandOptions.cveVariantId);
        queryParams.putIfNotNull("cvePrimaryFinding", commandOptions.cvePrimaryFinding);
        queryParams.putIfNotNull("cvePrimaryInterpretation", commandOptions.cvePrimaryInterpretation);
        queryParams.putIfNotEmpty("cvePhenotypeName", commandOptions.cvePhenotypeName);
        queryParams.putIfNotEmpty("cveGeneName", commandOptions.cveGeneName);
        queryParams.putIfNotEmpty("cveTranscriptId", commandOptions.cveTranscriptId);
        queryParams.putIfNotEmpty("cveSoTermName", commandOptions.cveSoTermName);
        queryParams.putIfNotEmpty("cveXrefId", commandOptions.cveXrefId);
        queryParams.putIfNotEmpty("cvePanelId", commandOptions.cvePanelId);
        queryParams.putIfNotEmpty("cveMoi", commandOptions.cveMoi);
        queryParams.putIfNotEmpty("cvePenetrance", commandOptions.cvePenetrance);
        queryParams.putIfNotEmpty("cveAcmg", commandOptions.cveAcmg);
        queryParams.putIfNotEmpty("cveTier", commandOptions.cveTier);
        queryParams.putIfNotEmpty("cveClinicalSignificance", commandOptions.cveClinicalSignificance);
        queryParams.putIfNotEmpty("cveDrugResponse", commandOptions.cveDrugResponse);
        queryParams.putIfNotEmpty("cveTraitAssociation", commandOptions.cveTraitAssociation);
        queryParams.putIfNotEmpty("cveFunctionalEffect", commandOptions.cveFunctionalEffect);
        queryParams.putIfNotEmpty("cveTumorigenesis", commandOptions.cveTumorigenesis);
        queryParams.putIfNotEmpty("cveOtherClassification", commandOptions.cveOtherClassification);
        queryParams.putIfNotEmpty("cveRoleInCancer", commandOptions.cveRoleInCancer);
        queryParams.putIfNotEmpty("cveReviewAcmg", commandOptions.cveReviewAcmg);
        queryParams.putIfNotEmpty("cveReviewTier", commandOptions.cveReviewTier);
        queryParams.putIfNotEmpty("cveReviewClinicalSignificance", commandOptions.cveReviewClinicalSignificance);
        queryParams.putIfNotEmpty("cveReviewText", commandOptions.cveReviewText);
        queryParams.putIfNotEmpty("field", commandOptions.field);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return enterpriseOpenCGAClient.getEnterpriseCvdbAnalysisClient().aggregateVariantEvidence(queryParams);
    }

    private RestResponse<ClinicalVariantEvidence> queryVariantEvidence() throws Exception {
        logger.debug("Executing queryVariantEvidence in CVDB command line");

        CVDBCommandOptions.QueryVariantEvidenceCommandOptions commandOptions = cVDBCommandOptions.queryVariantEvidenceCommandOptions;

        ObjectMap queryParams = new ObjectMap();
        queryParams.putIfNotEmpty("project", commandOptions.project);
        queryParams.putIfNotEmpty("study", commandOptions.study);
        queryParams.putIfNotEmpty("include", commandOptions.include);
        queryParams.putIfNotEmpty("exclude", commandOptions.exclude);
        queryParams.putIfNotNull("limit", commandOptions.limit);
        queryParams.putIfNotNull("skip", commandOptions.skip);
        queryParams.putIfNotEmpty("caId", commandOptions.caId);
        queryParams.putIfNotEmpty("caDescription", commandOptions.caDescription);
        queryParams.putIfNotEmpty("caType", commandOptions.caType);
        queryParams.putIfNotEmpty("caDisorderId", commandOptions.caDisorderId);
        queryParams.putIfNotEmpty("caFilename", commandOptions.caFilename);
        queryParams.putIfNotEmpty("caProbandId", commandOptions.caProbandId);
        queryParams.putIfNotEmpty("caProbandDisorderId", commandOptions.caProbandDisorderId);
        queryParams.putIfNotEmpty("caProbandPhenotypeName", commandOptions.caProbandPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyId", commandOptions.caFamilyId);
        queryParams.putIfNotEmpty("caFamilyPhenotypeName", commandOptions.caFamilyPhenotypeName);
        queryParams.putIfNotEmpty("caFamilyMemberId", commandOptions.caFamilyMemberId);
        queryParams.putIfNotEmpty("caReport", commandOptions.caReport);
        queryParams.putIfNotEmpty("caStatus", commandOptions.caStatus);
        queryParams.putIfNotNull("caLocked", commandOptions.caLocked);
        queryParams.putIfNotEmpty("ciId", commandOptions.ciId);
        queryParams.putIfNotNull("ciPrimary", commandOptions.ciPrimary);
        queryParams.putIfNotEmpty("ciDescription", commandOptions.ciDescription);
        queryParams.putIfNotEmpty("ciPanelId", commandOptions.ciPanelId);
        queryParams.putIfNotEmpty("ciAnalystId", commandOptions.ciAnalystId);
        queryParams.putIfNotEmpty("ciAnalystName", commandOptions.ciAnalystName);
        queryParams.putIfNotEmpty("ciAnalystEmail", commandOptions.ciAnalystEmail);
        queryParams.putIfNotEmpty("ciAnalystAssignedBy", commandOptions.ciAnalystAssignedBy);
        queryParams.putIfNotEmpty("ciAnalystDate", commandOptions.ciAnalystDate);
        queryParams.putIfNotEmpty("ciMethodName", commandOptions.ciMethodName);
        queryParams.putIfNotEmpty("ciMethodVersion", commandOptions.ciMethodVersion);
        queryParams.putIfNotEmpty("ciMethodCommit", commandOptions.ciMethodCommit);
        queryParams.putIfNotEmpty("ciMethodDependencies", commandOptions.ciMethodDependencies);
        queryParams.putIfNotEmpty("ciComments", commandOptions.ciComments);
        queryParams.putIfNotNull("ciLocked", commandOptions.ciLocked);
        queryParams.putIfNotEmpty("ciStatusId", commandOptions.ciStatusId);
        queryParams.putIfNotEmpty("ciStatusName", commandOptions.ciStatusName);
        queryParams.putIfNotEmpty("ciStatusDescription", commandOptions.ciStatusDescription);
        queryParams.putIfNotEmpty("ciStatusDate", commandOptions.ciStatusDate);
        queryParams.putIfNotEmpty("ciCreationDate", commandOptions.ciCreationDate);
        queryParams.putIfNotEmpty("ciModificationDate", commandOptions.ciModificationDate);
        queryParams.putIfNotNull("ciVersion", commandOptions.ciVersion);
        queryParams.putIfNotEmpty("cvId", commandOptions.cvId);
        queryParams.putIfNotEmpty("cvVariantId", commandOptions.cvVariantId);
        queryParams.putIfNotNull("cvPrimaryFinding", commandOptions.cvPrimaryFinding);
        queryParams.putIfNotNull("cvPrimaryInterpretation", commandOptions.cvPrimaryInterpretation);
        queryParams.putIfNotEmpty("cvComments", commandOptions.cvComments);
        queryParams.putIfNotEmpty("cvDiscussionAuthor", commandOptions.cvDiscussionAuthor);
        queryParams.putIfNotEmpty("cvDiscussionDate", commandOptions.cvDiscussionDate);
        queryParams.putIfNotEmpty("cvDiscussionText", commandOptions.cvDiscussionText);
        queryParams.putIfNotEmpty("cvConfidenceValue", commandOptions.cvConfidenceValue);
        queryParams.putIfNotEmpty("cvConfidenceAuthor", commandOptions.cvConfidenceAuthor);
        queryParams.putIfNotEmpty("cvConfidenceDate", commandOptions.cvConfidenceDate);
        queryParams.putIfNotEmpty("cvTag", commandOptions.cvTag);
        queryParams.putIfNotEmpty("cvStatus", commandOptions.cvStatus);
        queryParams.putIfNotEmpty("cvRegion", commandOptions.cvRegion);
        queryParams.putIfNotEmpty("cvBiotype", commandOptions.cvBiotype);
        queryParams.putIfNotEmpty("cvCt", commandOptions.cvCt);
        queryParams.putIfNotEmpty("cvTranscriptFlag", commandOptions.cvTranscriptFlag);
        queryParams.putIfNotEmpty("cvGene", commandOptions.cvGene);
        queryParams.putIfNotEmpty("cvXref", commandOptions.cvXref);
        queryParams.putIfNotEmpty("cvAnnotRoleInCancerGenes", commandOptions.cvAnnotRoleInCancerGenes);
        queryParams.putIfNotEmpty("cvType", commandOptions.cvType);
        queryParams.putIfNotEmpty("cvProteinSubstitution", commandOptions.cvProteinSubstitution);
        queryParams.putIfNotEmpty("cvConservation", commandOptions.cvConservation);
        queryParams.putIfNotEmpty("cvFunctionalScore", commandOptions.cvFunctionalScore);
        queryParams.putIfNotEmpty("cvPopulationFrequencyAlt", commandOptions.cvPopulationFrequencyAlt);
        queryParams.putIfNotEmpty("cvPopulationFrequencyMaf", commandOptions.cvPopulationFrequencyMaf);
        queryParams.putIfNotEmpty("cvPopulationFrequencyRef", commandOptions.cvPopulationFrequencyRef);
        queryParams.putIfNotEmpty("cvCohortStatsAlt", commandOptions.cvCohortStatsAlt);
        queryParams.putIfNotEmpty("cvCohortStatsMaf", commandOptions.cvCohortStatsMaf);
        queryParams.putIfNotEmpty("cvCohortStatsRef", commandOptions.cvCohortStatsRef);
        queryParams.putIfNotEmpty("cvCohortStatsPass", commandOptions.cvCohortStatsPass);
        queryParams.putIfNotEmpty("cvScore", commandOptions.cvScore);
        queryParams.putIfNotEmpty("cvAnnotGoGenes", commandOptions.cvAnnotGoGenes);
        queryParams.putIfNotEmpty("cvAnnotExpressionGenes", commandOptions.cvAnnotExpressionGenes);
        queryParams.putIfNotEmpty("cvGeneTraitId", commandOptions.cvGeneTraitId);
        queryParams.putIfNotEmpty("cvTrait", commandOptions.cvTrait);
        queryParams.putIfNotEmpty("cvProteinKeyword", commandOptions.cvProteinKeyword);
        queryParams.putIfNotEmpty("cveVariantId", commandOptions.cveVariantId);
        queryParams.putIfNotNull("cvePrimaryFinding", commandOptions.cvePrimaryFinding);
        queryParams.putIfNotNull("cvePrimaryInterpretation", commandOptions.cvePrimaryInterpretation);
        queryParams.putIfNotEmpty("cvePhenotypeName", commandOptions.cvePhenotypeName);
        queryParams.putIfNotEmpty("cveGeneName", commandOptions.cveGeneName);
        queryParams.putIfNotEmpty("cveTranscriptId", commandOptions.cveTranscriptId);
        queryParams.putIfNotEmpty("cveSoTermName", commandOptions.cveSoTermName);
        queryParams.putIfNotEmpty("cveXrefId", commandOptions.cveXrefId);
        queryParams.putIfNotEmpty("cvePanelId", commandOptions.cvePanelId);
        queryParams.putIfNotEmpty("cveMoi", commandOptions.cveMoi);
        queryParams.putIfNotEmpty("cvePenetrance", commandOptions.cvePenetrance);
        queryParams.putIfNotEmpty("cveAcmg", commandOptions.cveAcmg);
        queryParams.putIfNotEmpty("cveTier", commandOptions.cveTier);
        queryParams.putIfNotEmpty("cveClinicalSignificance", commandOptions.cveClinicalSignificance);
        queryParams.putIfNotEmpty("cveDrugResponse", commandOptions.cveDrugResponse);
        queryParams.putIfNotEmpty("cveTraitAssociation", commandOptions.cveTraitAssociation);
        queryParams.putIfNotEmpty("cveFunctionalEffect", commandOptions.cveFunctionalEffect);
        queryParams.putIfNotEmpty("cveTumorigenesis", commandOptions.cveTumorigenesis);
        queryParams.putIfNotEmpty("cveOtherClassification", commandOptions.cveOtherClassification);
        queryParams.putIfNotEmpty("cveRoleInCancer", commandOptions.cveRoleInCancer);
        queryParams.putIfNotEmpty("cveReviewAcmg", commandOptions.cveReviewAcmg);
        queryParams.putIfNotEmpty("cveReviewTier", commandOptions.cveReviewTier);
        queryParams.putIfNotEmpty("cveReviewClinicalSignificance", commandOptions.cveReviewClinicalSignificance);
        queryParams.putIfNotEmpty("cveReviewText", commandOptions.cveReviewText);
        if (queryParams.get("study") == null && OpencgaMain.isShellMode()) {
            queryParams.putIfNotEmpty("study", sessionManager.getSession().getCurrentStudy());
        }

        return enterpriseOpenCGAClient.getEnterpriseCvdbAnalysisClient().queryVariantEvidence(queryParams);
    }
}