<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zettagenomics.opencga-enterprise</groupId>
        <artifactId>opencga-enterprise</artifactId>
        <version>1.6.0-SNAPSHOT</version>
    </parent>

    <artifactId>opencga-enterprise-server</artifactId>
    <packaging>war</packaging>

    <name>opencga-enterprise-server Maven Webapp</name>
    <url>http://maven.apache.org</url>
    <dependencies>
        <dependency>
            <groupId>com.zettagenomics.opencga-enterprise</groupId>
            <artifactId>opencga-enterprise-core</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-catalog</artifactId>
            <version>2.8.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-storage-core</artifactId>
            <version>2.8.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.opencb.opencga</groupId>
            <artifactId>opencga-server</artifactId>
            <version>2.8.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.opencb.biodata</groupId>
            <artifactId>biodata-tools</artifactId>
            <version>2.8.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>opencga-enterprise-server</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.4.0.Final</version>
            </extension>
        </extensions>
        <plugins>
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <warName>${opencga.war.name}</warName>
                    <!--
                      Exclude JCL and LOG4J since all logging should go through SLF4J.
                      Note that we're excluding log4j-<version>.jar but keeping
                      log4j-over-slf4j-<version>.jar
                    -->
                    <!--<packagingExcludes>-->
                    <!--WEB-INF/lib/commons-logging-*.jar,-->
                    <!--%regex[WEB-INF/lib/log4j-(?!over-slf4j).*.jar]-->
                    <!--</packagingExcludes>-->
                    <webResources>
                        <resource>
                            <directory>src/main/webapp/WEB-INF/</directory>
                            <filtering>true</filtering>
                            <targetPath>WEB-INF</targetPath>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <id>make-a-jar</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-install-plugin</artifactId>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <phase>install</phase>-->
<!--                        <goals>-->
<!--                            <goal>install-file</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <packaging>jar</packaging>-->
<!--                            <groupId>${project.groupId}</groupId>-->
<!--                            <artifactId>${project.artifactId}</artifactId>-->
<!--                            <version>${project.version}</version>-->
<!--                            <file>-->
<!--                                ${project.build.directory}/${project.artifactId}-${project.version}.jar-->
<!--                            </file>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>GenerateCLIProfile</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.0.0</version>
                        <executions>
                            <execution>
                                <id>CLIWriter</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>java</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <mainClass>com.zettagenomics.opencga.enterprise.server.generator.EnterpriseClientsGeneratorMain</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
