name: Build clients for opencga

on:
  workflow_dispatch:

jobs:
  build-clients:
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '10'
      - id: get_opencga_branch
        name: Get OpenCGA branch from pom.xml property
        run: |
          chmod +x ./.github/workflows/scripts/opencga_branch.sh
          opencga_branch=$(./.github/workflows/scripts/opencga_branch.sh "${{ inputs.release }}" )
          echo "OpenCGA ref: __\"${opencga_branch}\"__" | tee -a ${GITHUB_STEP_SUMMARY}
          echo "Is release: __\"${{ inputs.release }}\"__" | tee -a ${GITHUB_STEP_SUMMARY}
          echo "opencga_branch=${opencga_branch}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          repository: opencb/opencga
          ref: ${{ steps.get_opencga_branch.outputs.opencga_branch }}
          path: opencga-home
          fetch-depth: '10'

      - name: Build clients
        run: |
          chmod +x build_clients.sh 
          ./build_clients.sh
      - name: Upload clients folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: clients
          path: build/dist