name: "Reusable workflow to push in DockerHub"

on:
  workflow_call:
    input:
      artifact_name:
        type: string
        required: true
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  deploy-docker-hub:
    name: Push Docker image
    runs-on: ubuntu-22.04
    steps:
      - name: Download build dir
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: build
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push in Docker Hub
        run: python3 ./build/cloud/docker/docker-build.py push --org zettagenomics --images base