name: Deploy OpenCGA Enterprise EMR to DockerHub

on:
  workflow_call:
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  build:
    uses: ./.github/workflows/build-java-enterprise-workflow.yml
    with:
      maven_opts: -Dopencga.war.name=opencga
      opencga_maven_opts: -P storage-hadoop,emr6.1
      artifact_name: emr-build-folder

  deploy-docker-hub:
    name: Push Docker image
    runs-on: ubuntu-22.04
    steps:
      - name: Download build dir
        uses: actions/download-artifact@v3
        with:
          name: emr-build-folder
          path: build
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push in Docker Hub
        run: python3 ./build/cloud/docker/docker-build.py push --org zettagenomics --images base