name: Deploy OpenCGA Enterprise HDP to DockerHub

on:
  workflow_call:
    inputs:
      options:
        type: string
        required: false
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  deploy-docker-hub:
    name: Push Docker image
    runs-on: ubuntu-22.04
    steps:
      - name: Download build dir
        uses: actions/download-artifact@v3
        with:
          name: build-folder
          path: build
      - name: Chmod
        run: "find build -regex '.*sh' | while read file ; do chmod u+x $file ; done"
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push in Docker Hub
        run: python3 ./build/cloud/docker/docker-build.py push --org zettagenomics --images enterprise ${{ inputs.options }}