name: Reusable workflow to build Java application

on:
  workflow_call:
    inputs:
      storage_hadoop:
        type: string
        required: false
      artifact_name:
        type: string
        required: false
      release:
        type: string
        required: false
    outputs:
      version:
        description: "XetaBase project version"
        value: ${{ jobs.build.outputs.version }}

jobs:
  deploy-docker-hub:
    name: Push Docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Download build dir
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: build
      - name: Chmod
        run: "find build -regex '.*sh' | while read file ; do chmod u+x $file ; done"
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push in Docker Hub
        run: |
          set -e
          chmod +x ./.github/workflows/scripts/opencga_enterprise_docker_tag.sh
          tag=$(./.github/workflows/scripts/opencga_enterprise_docker_tag.sh)
          python3 ./build/cloud/docker/docker-build.py push --org zettagenomics --images enterprise --tag "$tag"