name: Push opencga-enterprise develop or release branch

on:
  push:
    branches:
      - develop
      - release-*
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-java-enterprise-workflow.yml
    with:
      maven_opts: -Dopencga.war.name=opencga

  deploy-docker:
    uses: ./.github/workflows/deploy-docker-hub-enterprise-workflow.yml
    needs: build
    secrets: inherit
