name: Push opencga-enterprise develop or release branch

on:
  push:
    branches:
      - develop
      - release-*

jobs:
  build:
    uses: zetta-genomics/opencga-enterprise/.github/workflows/build-java-enterprise-workflow.yml@TASK-1974
    with:
      maven_opts: -Dopencga.war.name=opencga -P CodeGen

  deploy-docker:
    uses: zetta-genomics/opencga-enterprise/.github/workflows/deploy-enterprise-docker-hub-workflow.yml@TASK-1974
    needs: build
    secrets: inherit
