name: Push ext-tools for develop branches

on:
  push:
    branches:
      - develop
      - release-*
      - TASK-*
  workflow_dispatch:

jobs:

  check-docker-tag:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check.outputs.exists }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Make script executable
        run: chmod +x .github/workflows/scripts/check_docker_tag.sh
      - name: Check Docker tag existence
        id: check
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          .github/workflows/scripts/check_docker_tag.sh

  deploy-docker-ext-tools:
    needs: check-docker-tag
    if: needs.check-docker-tag.outputs.exists == 'false'
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    with:
      cli: python3 ./opencga-app/app/cloud/docker/docker-build.py push --images ext-tools --tag ${{ needs.check-docker-tag.outputs.version }}
    secrets: inherit




