name: Deploy Docker Ext-Tools

on:
  push:
    paths:
      - opencga-app/app/cloud/docker/opencga-ext-tools/Dockerfile

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop
    with:
      needs_hadoop_preparation: true
      hadoop_flavour: ${{ vars.HADOOP_FLAVOUR }}
      maven_opts: -P${{ vars.HADOOP_FLAVOUR }} -Dopencga.war.name=opencga -Dcheckstyle.skip
    secrets: inherit

  deploy-docker-ext-tools:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    needs: build
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images ext-tools --tag ${{ needs.build.outputs.version }}
    secrets: inherit