name: Manual build R
on:
  workflow_dispatch:

jobs:
  call-build-r-docker:
    name: Call Reusable Build r Docker Workflow
    uses: zetta-genomics/opencga-enterprise/.github/workflows/reusable-build-r-clientyml@develop
    secrets: inherit
