

name: Manual build workflow

on:
  workflow_dispatch:
    inputs:
      maven_opts:
        type: string
        required: false
        
jobs:
  build:
    uses: ./.github/workflows/build-java-enterprise-workflow.yml
    with:
      maven_opts: ${{ inputs.maven_opts }}
