name: "Pull Request Merge Workflow"

on:
  pull_request:
    branches:
      - "develop"
      - "release-*"
    types:
      - closed

jobs:
  delete-docker:
    name: Execute delete docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '10'
      - name: delete docker images
        run: |
          echo "Deleting docker images"
          python3 ./opencga-app/app/cloud/docker/docker-build.py delete --images base,workflow --tag ${{ github.head_ref }}

