name: "Pull Request Merge Workflow"

on:
  pull_request:
    branches:
      - "develop"
      - "release-*"
    types:
      - closed

jobs:
  docker-delete:
    name: Delete TASK Docker image
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout opencga"
        uses: actions/checkout@v3
      - run: python3 ./opencga-app/app/cloud/docker/docker-build.py delete --images base --tag ${{ github.ref_name }} --username ${{ secrets.DOCKER_HUB_USER }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
