name: Pull request approve workflow

on:
  pull_request_review:
    types: [submitted]

jobs:
  test:
    name: Execute JUnit and Jacoco tests
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KEEPER_SM_GH_ZETTAGENOMICS }}
          secrets: |
            AZURE_KUBE_CONFIG/field/Secret Value > env:AZURE_KUBE_CONFIG
            DOCKER_HUB_USER/field/Secret Value > env:DOCKER_HUB_USER
            DOCKER_HUB_PASSWORD/field/Secret Value > env:DOCKER_HUB_PASSWORD
            SSH_TESTING_SERVER_HOST/field/Secret Value > env:SSH_HOST
            SSH_TESTING_SERVER_PORT/field/Secret Value > env:SSH_PORT
            SSH_TESTING_SERVER_USER/field/Secret Value > env:SSH_USER
            SSH_TESTING_SERVER_PASSWORD/field/Secret Value > env:SSH_PASS
      - name: Clone OpenCGA Enterprise branch '${{ github.event.pull_request.head.ref }}'
        uses: actions/checkout@v4
        with:
          repository: zetta-genomics/opencga-enterprise
          token: ${{ secrets.GH_PRIVATE_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: "0" # Perform a full clone, not a shallow one to build.sh can get the branch name
      - id: get_opencga_branch
        name: Get current branch for opencga from 'pom.xml' property
        run: |
          pwd
          chmod +x ./.github/workflows/scripts/get-opencga-xetabase-branch.sh
          opencga_branch=$(./.github/workflows/scripts/get-opencga-xetabase-branch.sh  ${{ github.event.pull_request.head.ref }})
          echo "__OpenCGA ref:__ \"${opencga_branch}\"" | tee -a ${GITHUB_STEP_SUMMARY}
          echo "opencga_branch=${opencga_branch}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          repository: opencb/opencga
          ref: ${{ steps.get_opencga_branch.outputs.opencga_branch }}
          path: opencga-home
          fetch-depth: "0" # Perform a full clone, not a shallow one to build.sh can get the branch name
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Install Samtools
        run: sudo apt-get install samtools python3-deeptools
      - name: Start MongoDB v6.0
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0
          mongodb-replica-set: rs-test
      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      - name: K8s Tunnel MongoDB
        run: |
          wget https://dl.k8s.io/release/v1.28.2/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          echo "${{ env.AZURE_KUBE_CONFIG }}" > admin.conf
          ./kubectl -n cellbase-db port-forward services/cellbase-rs0-svc 27018:27017 --kubeconfig ./admin.conf &
      - name: Install sshpass
        run: sudo apt-get install sshpass
      - name: Add SSH Host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ env.SSH_PORT }} ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ env.SSH_HOST }}
          SSH_PORT: ${{ env.SSH_PORT }}
      - name: Run all OpenCB Junit tests, ie. java-common-libs, biodata, cellbase, opencga and opencga-enterprise
        run: |
         ./build.sh -t -l runShortTests -d -b -s -T ${{ github.event.pull_request.head.ref }} -c localhost:27018 -H hdp3.1
