name: "Pull Request Merge Workflow"

on:
  pull_request:
    branches:
      - "develop"
      - "release-*"
    types:
      - closed

jobs:
  delete-docker:
    uses: opencb/java-common-libs/.github/workflows/delete-docker-hub-workflow.yml@develop
    with:
      cli: python3 ./build/cloud/docker/docker-build.py delete --images base --tag ${{ github.head_ref }}
    secrets: inherit
