name: Pull request approve workflow

on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop
    with:
      maven_opts: -Phdp3.1,RClient -Dopencga.war.name=opencga -Dcheckstyle.skip

  test:
    name: "Run all tests before merging, ie. short, medium and long tests."
    uses: ./.github/workflows/test-analysis.yml
    needs: build
    with:
      test_profile: runShortTests,runMediumTests,runLongTests
    secrets: inherit
