name: "Pull Request Merge Workflow"

on:
  pull_request:
    branches:
      - "develop"
      - "release-*"
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop
    with:
      maven_opts: -P hdp3.1,RClient -Dopencga.war.name=opencga -Dcheckstyle.skip

  delete-docker:
    uses: opencb/java-common-libs/.github/workflows/delete-docker-hub-workflow.yml@develop
    needs: build
    with:
      cli: python3 ./build/cloud/docker/docker-build.py delete --images base,workflow --tag ${{ github.head_ref }}
    secrets: inherit

