name: Release new opencga-enterprise version

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build-java-enterprise-workflow.yml
    with:
      maven_opts: -Dopencga.war.name=opencga
      opencga_maven_opts: -P storage-hadoop,hdp3.1
      artifact_name: build-folder
#      release: true

  deploy-hdp-docker:
    uses: ./.github/workflows/deploy-docker-hub-enterprise-workflow.yml
    needs: build
    secrets: inherit
    with:
      artifact_name: build-folder

  build-emr:
    uses: ./.github/workflows/build-java-enterprise-workflow.yml
    needs: deploy-hdp-docker
    with:
      maven_opts: -Dopencga.war.name=opencga
      opencga_maven_opts: -P storage-hadoop,emr6.1
      artifact_name: emr-build-folder
#      release: true

  deploy-emr-docker:
    uses: ./.github/workflows/deploy-docker-hub-enterprise-workflow.yml
    needs:  build-emr
    secrets: inherit
    with:
      artifact_name: emr-build-folder

#  release:
#    name: Create GitHub Release
#    runs-on: ubuntu-22.04
#    needs: [ build, deploy-emr-docker ]
#    steps:
#      - uses: actions/download-artifact@v3
#        with:
#          name: build-folder
#      - name: GitHub Release
#        uses: softprops/action-gh-release@v1
#        with:
#          name: ${{ github.ref_name }}
#          tag_name: ${{ github.ref }}
#          generate_release_notes: true
#          files: |
#            opencga-enterprise-client-${{ needs.build.outputs.version }}.tar.gz
