name: Build opencga python-client

on:
  workflow_call:

jobs:
  build-python-client:
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '10'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build R client
        run: |
          ./build_clients.sh --skip-r --skip-javascript
      - uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: build
      - name: Upload built python client package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: opencga-python-client-${{ steps.version.outputs.version }}.tar.gz
          path: build/dist/opencga-python-client-${{ steps.version.outputs.version }}.tar.gz

  deploy-python:
    uses: opencb/java-common-libs/.github/workflows/deploy-python-workflow.yml@develop
    needs: build-python-client
    with:
      cli: ./clients/python/python-build.sh push
      artifact: build-folder
    secrets: inherit