name: Build and Test opencga-r-builder Docker Image

on:
  workflow_call:
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  build-test-publish:
    runs-on: ${{ vars.UBUNTU_VERSION }}
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: build
      - name: Build Docker image
        run: |
          build_clients.sh --skip-python --skip-javascript 
      - name: Extract version from DESCRIPTION
        id: version
        run: |
          VERSION=$(grep '^Version:' build/clients/R/DESCRIPTION | cut -d' ' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          ls build/
      - name: Upload built R package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: opencgaR_${{ steps.version.outputs.version }}.tar.gz
          path: build/dist/opencgaR_${{ steps.version.outputs.version }}.tar.gz