name: Reusable delete docker workflow from DockerHub

on:
  workflow_call:
    inputs:
      task:
        type: string
        required: true
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  delete-docker:
    name: Execute delete docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '10'
      - name: Validate task name
        if: ${{ !startsWith(inputs.task, 'TASK') }}
        run: |
          echo "Error: Can't delete ${{ inputs.task }}. Only Docker images related to TASK branches can be deleted"
          exit 1
      - name: Delete in Docker Hub
        if: ${{ startsWith(inputs.task, 'TASK') }}
        run: |
          echo "Deleting docker image ${{ inputs.task }}"
          python3 ./opencga-app/app/cloud/docker/docker-build.py delete --images base,workflow --tag ${{ inputs.task }} --username ${{ secrets.DOCKER_HUB_USER }} --password ${{ secrets.DOCKER_HUB_PASSWORD }} --org zettagenomics