name: Build and Test opencga-r-builder Docker Image

on:
  workflow_call:
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop
    with:
      maven_opts: -Phdp3.1,RClient -Dopencga.war.name=opencga -Dcheckstyle.skip
      build_folder: build-folder

  build-test-publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t opencb/opencga-r-builder:dev \
            -f opencga-app/app/cloud/docker/opencga-r-builder/Dockerfile \
            opencga-app/app/cloud/docker/opencga-r-builder

      - name: Test R CMD build inside container
        run: |
          docker run --rm \
            --mount type=bind,source="${{ github.workspace }}/build/clients/R",target=/opt/opencga/R \
            --mount type=bind,source="${{ github.workspace }}/build",target=/opt/opencga \
            opencb/opencga-r-builder:dev \
            R CMD build /opt/opencga/R

      - uses: actions/upload-artifact@v4
        with:
          name: r-build
          path: build