name: Build opencga python-client

on:
  workflow_call:
    inputs:
      branch:
        description: "The branch, tag or SHA of the source code to build client."
        type: string
        required: true

jobs:
  build-python-client:
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '10'
          ref: ${{ inputs.branch }}
      - id: get_opencga_branch
        name: Get OpenCGA branch from pom.xml property
        run: |
          chmod +x ./.github/workflows/scripts/opencga_branch.sh
          opencga_branch=$(./.github/workflows/scripts/opencga_branch.sh "${{ inputs.release }}" )
          echo "OpenCGA ref: __\"${opencga_branch}\"__" | tee -a ${GITHUB_STEP_SUMMARY}
          echo "Is release: __\"${{ inputs.release }}\"__" | tee -a ${GITHUB_STEP_SUMMARY}
          echo "opencga_branch=${opencga_branch}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          repository: opencb/opencga
          ref: ${{ steps.get_opencga_branch.outputs.opencga_branch }}
          path: opencga-home
          fetch-depth: '10'
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Python client
        run: |
          ./client-builder.sh --skip-r --skip-javascript
      - uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: build
      - name: Upload built python client package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: opencga-enterprise-python-client-${{ steps.version.outputs.version }}.tar.gz
          path: build/dist/opencga-enterprise-python-client-${{ steps.version.outputs.version }}.tar.gz

  deploy-python:
    uses: opencb/java-common-libs/.github/workflows/deploy-python-workflow.yml@develop
    needs: build-python-client
    with:
      cli: ./clients/python/python-build.sh push
      artifact: build-folder
    secrets:
      PYPI_TWINE_USER: ${{ secrets.PYPI_TWINE_USER }}
      PYPI_TWINE_PASSWORD: ${{ secrets.PYPI_TWINE_PASSWORD }}