name: Push OpenCGA TASK

on:
  push:
    branches:
      - TASK-*
  workflow_dispatch:
    inputs:
      branch:
        description: 'Execute workflow'
        default: 'develop'
        required: true

jobs:
  build:
    uses: ./.github/workflows/build-java-enterprise-workflow.yml
    with:
      storage_hadoop: hdp3.1
      artifact_name: build-folder

  deploy-docker:
    uses: ./.github/workflows/deploy-docker-hub-enterprise-workflow.yml
    needs: build
    secrets: inherit
    with:
      artifact_name: build-folder
