name: Push OpenCGA TASK

on:
  push:
    branches:
      - TASK-*
  workflow_dispatch:

jobs:
  build-opencga:
    name: Build OpenCGA app
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: opencb/opencga
          ref: develop
          fetch-depth: '10'
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Maven Build (skip tests)
        run: mvn -T 2 clean deploy -DskipTests -P deploy
      - uses: actions/upload-artifact@v3
        with:
          name: opencga-build-folder
          path: build

  build:
    name: Build OpenCGA Enterprise app
    runs-on: ubuntu-22.04
    needs: build-opencga
    outputs:
      version: ${{ steps.get_project_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '10'
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Download OpenCGA
        uses: actions/download-artifact@v3
        with:
          name: opencga-build-folder
          path: opencga-home
      - name: Maven Build (skip tests)
        run: mvn -T 2 clean install -DskipTests
      - uses: actions/upload-artifact@v3
        with:
          name: build-folder
          path: build
      - id: get_project_version
        uses: avides/actions-project-version-check@v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: pom.xml
          only-return-version: true
      - name: test-version-from-check
        run: echo "Project version is " ${{ steps.get_project_version.outputs.version }}

#  test:
#    uses: zettagenomics/opencga-enterprise/.github/workflows/build-analysis.yml@develop
#    needs: build
#    secrets: inherit

  deploy-docker:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    needs: build
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images base,init
    secrets: inherit
