name: To test cicd

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-java-enterprise-workflow.yml
    with:
      maven_opts: -Dopencga.war.name=opencga
      opencga_maven_opts: -P storage-hadoop,${{ vars.HADOOP_FLAVOUR }}
      artifact_name: build-folder
    secrets: inherit

  deploy-docker:
    uses: ./.github/workflows/deploy-docker-hub-enterprise-workflow.yml
    needs: build
    secrets: inherit

  deploy-emr-docker:
    uses: ./.github/workflows/deploy-emr-docker-hub-enterprise-workflow.yml
    needs: build
    secrets: inherit